### ISSUE TITLE
Dynamically hide/show and unrequire/require state fields based on country.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1050]
## Issue Overview

We currently populate the state/province dropdown with separate state lists, depending on the country. Would be nice to (especially in places like the UK and Germany where there is no "state") either populate that field with "n/a" or make it go away all together. 

And it definitely needs to not be a required field if we don't have a case for it in the list at https://github.com/WordImpress/Give/blob/master/includes/country-functions.php#L60

**Comment by DevinWalker** [comment]
Good call @Benunc 

Please review how WooCommerce handles this per country. It's how I'd like our address fieldset to work when changing countries. Depending on the country:

1. If the country has states, display the state field - either as a text field or dropdown select if a list is available (like the US)
2. If the country does not have states, remove the field, it's not necessary

**TODO:** Test for this. Q: Does Woo have unit tests for this?

**Comment by raftaar1191** [comment]
Working on the about issue

**Comment by raftaar1191** [comment]
To Make the same that is being offered by WooCommerces we need to refactor the code.

1. **Recommendation on how we can achieve**
Need to make a list wherein country states are been added. If in the list country doest not find any states then no drop-down will not be shown and if it finds the states then there will be drop-down option show which will display the list of state that country has.

2.**our current functionality**
I have gone throughout our functionality we need to create some functions and need to depreciate the old one like the example: give_get_brazil_states_list which provided the list of states in Brazil and make all that thing into one array. Where in the key will be the country code and the value will be in array format containing the States pf the respected country.

3. **Time**
Around 10 hours.

**Comment by raftaar1191** [comment]
Notes where to check for dropdown
1> /wp-admin/edit.php?post_type=give_forms&page=give-donors&view=overview&id=3
2> http://localhost/givewp/wp-admin/edit.php?post_type=give_forms&page=give-payment-history&view=view-payment-details&id=1764

3> http://SITENAME/donations/first-form-all-fields-support-non-login-user-as-well/

**Comment by DevinWalker** [comment]
@raftaar1191 that sounds good. Let's proceed with the refactor.

**Comment by raftaar1191** [comment]
@ravinderk  
The above functionality is being added on the following PR please review and merge the PR
https://github.com/WordImpress/Give/pull/1858

**Comment by DevinWalker** [comment]
@raftaar1191 I noticed an issue with this functionality which is why I'm reopening it.

## Reopened Issue Description

If you notice how Woo works, the **label** _above_ the state field changes from just "State" (for instance the USA), to "State / Country" and "Province" according to the country selected. 

![2017-07-17_16-07-11](https://user-images.githubusercontent.com/1571635/28293661-1ad0c3a2-6b0a-11e7-93b7-1b584e5bf4bc.png)

![2017-07-17_16-07-33](https://user-images.githubusercontent.com/1571635/28293663-1c4a31dc-6b0a-11e7-8831-882c0e475bf2.png)

**_Our plugin should work exactly like this_**

Right now the label is simply "State / Province / Country" which is not an optimal UX. This is confusing to people in the US who are used to simply seeing "State". Likewise for other countries. 

Please fix and submit a new PR. Thanks

**Comment by raftaar1191** [comment]
Working on the above issues

**Comment by raftaar1191** [comment]
@DevinWalker @ravinderk 

Here is the PR https://github.com/WordImpress/Give/pull/1887 for the above issues
