### ISSUE TITLE
PayPal Standard: Add Fees as a Data Point

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1105]
## Issue Overview

Customer request for fees to be added in a way to be exported/reported.
## Expected Behavior

Add a field on a transaction for gateways who support it to report back how much of a transaction is fees, and record that as a meta on the give_payment post type
## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
This task should be broken up per gateway. Let's do it first with PayPal Standard.

**Comment by Asparagirl** [comment]
+1

This is important for bookkeeping so that we know how much we're spending on fees/expenses.

(Do Stripe next, please?  And maybe move to 2.0 or 1.9?)

**Comment by DevinWalker** [comment]
After thinking this through and how it can work I don't think this functionality would be good in core. Why? Well, because the one _true_ source for gateways should be the gateway itself. 

For intance, in Stripe you can find out the gateways fees via the monthly report, in PayPal you can as well get an accurate summary of fees in the reports. The issue is that with Give if an IPN (where we can pull in fee results) or webhook is missed then our data is inaccurate.

If you're using Fee Recovery you can export that fee data an compare against your payment gateway fees. That way you can compare how much you recovered vs how much was actually subtracted from your donations. I think that's the best way to handle fees within Give's internal database moving forward.
