### ISSUE TITLE
New top level pages..

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/Give#112]
Hey

I have the automatically add top level pages to the menu on the menu screen.
Which means that Donation Confirmation, Transaction Failed and Donation History all are automatically added to the menu.

If these were instead added as draft pages then they would not be added. Or if that is a bad option what about having them do not add to menu code or something similar to this.

**Comment by DevinWalker** [comment]
It sounds like you may have the option selected on your main menu "Automatically add new top level pages" - I don't think this is an issue and actually helps the user out a lot when setting up the plugin. Most users simply would think the plugin is broken otherwise. 

Thanks for taking a look at it though!

**Comment by paaljoachim** [comment]
Yup the option is selected. Alrighty. It really does remind one that the pages do exist. Easy enough to remove them from the menu.
