### ISSUE TITLE
Clarify structure of payment meta

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#1132]
## Issue Overview

The existing payment meta array exhibits some unexpected behavior outlined below.
### 1. Form email is stored twice

Both `['email']` and `['user_info']['email']` contain the email submitted in the form. It would be logical for `['user_info']['email']` to reflect the email associated with the user ID.
### 2. First and Last Name reflect name used on form, not user name

`['user_info']['first_name']` and `['user_info']['last_name']` reflect the name submitted in the form, not the name associated with the user ID. Need to decide if we want to store both user first/last names and first/last names entered on form.
### 3. Address is billing address, not user address

Looking at the payment meta array, `['user_info']['address']` appears to be the address of the user (aka donor). In fact, `['user_info']['address']` is the billing address entered on the form. It makes more sense in its own `['billing_address']` key, but that may present backwards compatibility issues. This decision affects #370.
### Example _give_payment_meta

See comments below that highlight the above discrepancies.

```
array(
    'key' => '8090dbc3144ae8e8460ede4b9459688f',
    'form_title' => 'All Fields Test Form',
    'email' => 'test@example.com', // email is from form, could be different from user
    'date' => '2016-10-09 13:07:55',
    'user_info' => array(
        'first_name' => 'Kevin', // name is from form, could be different from user
        'last_name' => 'Hoffman', // name is from form, could be different from user
        'id' => 1,
        'email' => 'test@example.com', // duplicate email is from form, could be different from user
        'address' => array( // this is actually billing address, not user address
            'line1' => '123 Billing St'
            'line2' => 'Apt 1'
            'city' => 'Pittsurgh'
            'state' => 'PA'
            'country' => 'US'
            'zip' => '15212'
        ),
    ),
    'form_id' => '220',
    'price_id' => '',
    'fees' => array(),
    'currency' => 'USD',
    'ffm_text' => 'Text Value',
    'ffm_textarea' => 'Textarea Value',
    'ffm_select' => 'Dropdown Option 1',
    'ffm_date' => '10/09/2016 13:04',
    'ffm_radio' => 'Radio Option 1',
    'ffm_checkbox' => 'Option 1| Option 2',
    'ffm_email' => 'ffm_test@example.com',
    'ffm_phone' => '(555) 555-5555',
    'ffm_url' => 'http://example.com',
    'ffm_multiselect' => 'Option 1| Option 2',
    'ffm_repeat' => array(
        0 => 'foo| bar',
        1 => 'baz| qux',
    ),
)
```
## Next Steps

In the case of First Name, Last Name, Email, and Address, the data entered in the form could be totally different from that of the user ID associated with the payment. We need to figure out how to handle that scenario while keeping an eye on backwards compatibility for existing sites that may be relying on the structure shown above.

**Comment by DevinWalker** [comment]
@ravinderk can you review this when you get a chance and provide your insight.

**Comment by ravinderk** [comment]
@DevinWalker Alright

**Comment by ravinderk** [comment]
@DevinWalker @kevinwhoffman Here are my thoughts on this:

### 1. Form email is stored twice
Yes, I think we can remove `['email']` with backward compatibility.

### 2. First and Last Name reflect name used on form, not user name
### 3. Address is billing address, not user address
`user_info` in payment meta is confusing term between user and donor, because it is donor data for specific donation expect containing user id instead of donor id. I think we can replace `['user_info']['id']` value with donor id and create new array key for user id. I am also agree to rename `address` to `billing_address` and  we can also rename `user_info` to `donor_info` then whole array data will become less confusing.


```
Array
(
    [key] => f2358650851aa52a053604a561dbb28c
    [form_title] => form testing
    [email] => ravinder+576-1@gmail.com
    [date] => 2016-10-20 17:25:38
    [user_info] => Array
        (
            [first_name] => Ravinder
            [last_name] => Kumar
            [id] => 22
            [email] => ravinder+576-1@gmail.com
            [address] => Array
                (
                    [line1] => street 1, Ujina
                    [line2] => street 2
                    [city] => gurgaon
                    [state] => HR
                    [country] => IN
                    [zip] => 122001
                )

        )

    [form_id] => 2120
    [price_id] => 
    [fees] => Array
        (
        )

    [currency] => USD
)
```




**Note [Bug]: when we view donation details then it always show primary email instead of new email (secondary)**
<img width="1049" alt="screen shot 2016-10-20 at 9 12 24 pm" src="https://cloud.githubusercontent.com/assets/1784821/19567566/c7bbe372-970b-11e6-903e-7e1495b19788.png">
<img width="843" alt="screen shot 2016-10-20 at 9 03 00 pm" src="https://cloud.githubusercontent.com/assets/1784821/19567565/c6f29b48-970b-11e6-81c0-c4acc1943896.png">

**Comment by kevinwhoffman** [comment]
@ravinderk Thanks for the feedback. I agree that the source of confusion comes down to the relationship between WordPress user and Give donor. Sometimes what appears to be donor information is actually user information and vice-versa. The confusion exists both in the structure of the `_give_payment_meta` array and in the interface as you noted in the bug above. I'll think on this some more and come back with a recommendation.

**Comment by drzraf** [comment]
Let me mention here issue #1296

* we do need **donor** meta (donor's address, birthday, ...) which, unlike **payment** meta, is unique (= deduplicated) for _all_ the payments this person does
I bet in most cases address only apply to donor rather than payment; in many countries the "address" is spontaneously seen as a personal information rather than as a financial information.  Another question is whether one user can have multiple set of addresses (most online shop softwares allow such a cardinality but should it be the case here?), user's _billing_ address is one specific case of a user having more than 1 address.

* IHMO neither _user_info_ nor _email_ have their place in payment/payment meta. User info = User meta. Payment entity should just contains **payment** information + references (to the ID of a set of payment **meta** (custom fields), to the ID a Give customer, ...).

* Like previously said, Give donor and WordPress user add to confusion. In #1296, it was said to be an additional feature to ease the life of the site owner. In such case, the "link" between a payment and a WordPress user (*_give_payment_user_id*) could be simply dropped since *wp_give_customers*' *user_id* already has the same purpose
(could even be implemented as a distinct Give plugin)
Creating as many WP user as there are donors isn't somewhat a niche-case? (Few people will really want to use WP as a CRM replacement)

**Comment by kevinwhoffman** [comment]
@drzraf Thanks for your feedback here. The points you bring up are exactly why we are looking at the structure of payment meta and user meta, where they overlap, and how to handle that overlap. We will be bringing more clarity to this situation as we work towards the 1.8 release.

**Comment by drzraf** [comment]
Any progress on this ?
I'd a look at the (changelog.txt-less) 1.9 branch, but couldn't figure anything related to this.
Is there W.I.P out there.

Personally I trying to fight the issue in our WP/Give instance.
I've setup a converter to the new scheme but having new donations respecting such a data structure using Give's hooks is (very) far from easy.
I'd be really happy to hear from you about the state of this moot issue.

**Comment by DevinWalker** [comment]
I understand it's difficult and we're shifting focus onto this once 1.8 is released. It's definitely an important priority.

**Comment by drzraf** [comment]
Currently, if Give is set to **not** create WordPress users, customers gets no "address" meta (only the payment does).
As a consequence, customer metas are not editable and even if customer "action" would do ``customer->update_meta("_give_user_address");`` that would make the Give customer edit-form to work since it only relies upon address from the WP User object's meta.

Given that I **need** editable customers **now** (not WordPress User) and that I'm in the process of converting metadata, my genuine question: I'd like to be futur-proof and intend to migrate payment's address meta into customers' "_give_user_address" meta (the same meta' name used for users).
Have you yet thought about using the very same name? Another one? Another name/mechanism?

sorry to be appear like pressuring about this, but I need to move on while avoiding reprocessing my database uselessly if 1.8 comes with something different.

**Comment by DevinWalker** [comment]
Thanks @ravinderk on this excellent PR: #1794
