### ISSUE TITLE
Translations not working when language codes do not match 100%

### ISSUE THREAD

**Issue by frickman** [WordImpress/Give#1143]
## Issue Overview
If your Wordpress-Blog's locale does not match the give locales 100%, give will fallback to english which it should not do in any case. It should fall back to the next "less specific" locale.

## Expected Behavior

de_CH_informal should fallback to de_CH, and de_CH should fallback to de. (Unspecific german is by far better than english ;-)
## Current Behavior

Currently, everything falls back to english.
## Possible Solution

No idea how to fix this with a wordpress plugin, but other tools are doing it exactly like this. Also, all other plugins are translating fine in my case. 
## Steps to Reproduce (for bugs)

1. Change Locale of Blog to de_CH_informal
2. Open a Give Form
3. Everything is english instead of german

**Comment by mathetos** [comment]
@frickman Ya, that's an interesting question, and I can see that as being important for sure.

@ramiy Do you have insight into this?

**Comment by ramiy** [comment]
## General Answer

I should start by saying that WordPress does not require 100% to create a language pack, it needs only 95% to triger GlotPress.

Give plugin, just like all other plugins/themes, uses WordPress Core functionally to load the translation files. We follow the wordpress coding standards to load translation strings.

We can't fallback to the next "less specific" locale when the plugin is not translated 100% to your local. We can't control this, it's handled by WordPress core.

## Specific Answer (German Language)

You mentioned that **de_CH_informal** should fallback to **de_CH**, and **de_CH** should fallback to **de**. If I'm not mistaking, there are several open tickets in WordPress Trac about this issue. I think they are not resolved yet.

In our case, I should mention that even if core will fix this behavior (locals fallbacks), it won't work on GIVE because [non of those languages was fully translated](https://translate.wordpress.org/projects/wp-plugins/give). German (DE) is the only language that has a [language pack](https://translate.wordpress.org/projects/wp-plugins/give/language-packs) but it was translated in Give 1.3.5 and not Give 1.6.2 (the latest plugin version). The other locals you mentioned never reached the 95% translation.

**Comment by DevinWalker** [comment]
@ramiy so there's not much we can do here besides continuing to promote helping us translate on via GlotPress on WordPress.org, correct? 

If you can find a link to the Core issue on Trac that would be great to read over how they are planning on handling that. It's an interesting question you have raised @frickman

**Comment by ramiy** [comment]
@DevinWalker 

Quick search on WordPress Core: https://core.trac.wordpress.org/ticket/28197

Maybe there are more tickets.

And I guess you will find more tickets on [Meta Trac](https://meta.trac.wordpress.org/query?component=Translate+Site+%26+Plugins&group=resolution&order=priority), because the main infrastructure is in translate.wordpress.org servers and in api.wordpress.org .

**Comment by DevinWalker** [comment]
Interesting. Thanks for the link, @ramiy. It looks like there's a few plugins that patch this issue as well: https://github.com/devinsays/fallback-languages and https://wordpress.org/plugins/language-fallback/

I'm going to close this out since it isn't an issue with Give.
