### ISSUE TITLE
Slowness on Transactions and Logs screens

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#1172]
## Issue Overview

With a full page of 30 test transactions, the Transactions and Logs screens are taking upwards of 7 seconds to load in Give `1.8.0`. Deleting all test transactions returns speed to normal.
## Expected Behavior

Transactions and Logs screens should load in a reasonable time less (less than 2 seconds). Future visits should be even faster if cached.
## Current Behavior

Transactions and Logs screens both take upwards of 7 seconds to load even after first visit.
## Possible Solution

Investigate what changed between `1.6.3` and `1.8.0` to cause this slowness.

Side note: Logs is the first tab of the Tools page in Give `1.8.0`. I suggest using a different default tab to avoid processing the logs report by default since the user's destination could be a different Tools tab.
## Steps to Reproduce (for bugs)
1. Create at least 30 test transactions to fill the page.
2. Visit the Transactions or Logs screen with Query Monitor plugin activated.
3. Note number of queries and time to load.
## Todos
- [ ] Develop set of Give test data.
- [ ] Compare `1.6.3` to `1.8.0` to see where this slowdown is occurring.

**Comment by ravinderk** [comment]
@kevinwhoffman @DevinWalker 
Here are My views on slowness of log's screen:

Take a look at this code https://github.com/WordImpress/Give/blob/master/includes/admin/reporting/class-sales-logs-list-table.php#L341#L363

We have six queries in if block and since we are showing 20 logs on each screen then total query becomes 120, which is the cause of slow loading.

We can reduce query but still we need `payment_id` (from each log) and there `Give_Payment` object (to retrieve data), so we still left with 40 query (slow loading)

We need to cache the results of each log screen conditionally to fix slow loading.


@DevinWalker Can you explain this more https://github.com/WordImpress/Give/blob/master/includes/admin/reporting/class-sales-logs-list-table.php#L325

**Comment by DevinWalker** [comment]
@kevinwhoffman @ravinderk there's definite slowness on this area. It's not just `release/1.8` that this is happening. I've prioritized the milestone to `release/1.7` so @ravinderk can dig in and provide recommendations/solutions to resolve the issue.
