### ISSUE TITLE
Allow admin to filter donations by form id

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1199]
## Issue Overview
<img width="1145" alt="screen shot 2016-11-02 at 2 53 15 pm" src="https://cloud.githubusercontent.com/assets/1784821/19923175/3a0ab5b6-a10c-11e6-81c3-1a2a08cbbc34.png">

## Possible Solution
Add a new filter which contains a list of donation forms in which admin can select specific form name if he/she want to filter donations by specific form id

Related To:
#621

**Comment by mathetos** [comment]
Not entirely, but maybe kinda related to: https://github.com/WordImpress/Give/issues/1190

Would ❤️ to see this implemented. The more tools we can give to Admins with our columns the better.

**Comment by amjad** [comment]
Is this not implemented yet? Form specific donations are a must have!

**Comment by kevinwhoffman** [comment]
You can currently sort donations by form when you click the `Donation Form` column header. I think what @ravinderk is suggesting is a dropdown field above the table that allows you to select a form so that _only_ that form's donations appear in the table below. Correct me if I'm wrong, @ravinderk :)

**Comment by ravinderk** [comment]
@kevinwhoffman you are right

**Comment by amjad** [comment]
Would be great to have a view donations link under each form in the all forms page.

**Comment by mathetos** [comment]
@amjad That would really clutter the form edit screen and cause it to lag since we'd have to query those donations. That's why there's a dedicated Reports section with Exports as well so you can see all your donations and per form as well.

You can also go to "Donations > All Forms" and then click on the Total Income number to see all donations for a particular form.

Lots of ways to do this. But this particular issue is about sorting the forms on the All Forms screen by Donation ID -- which we still need to implement.

**Comment by amjad** [comment]
Not in the same screen but it should take you to a page with only that form's donations list.

**Comment by mathetos** [comment]
@amjad You can do that from the "All Forms" screen. Click on the "Donations" link next to your form and you'll see only the transactions for that form.

Thanks!

**Comment by amjad** [comment]
👍🏻
