### ISSUE TITLE
Sorting by minimum amount

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1253]
## Issue Overview

Currently, we are sorting form list in wp-backend on basis of price which internally sorts form list on basis of `_give_set_price`. We will not get correct order if we also have some multi-level donation form
<img width="1041" alt="screen shot 2016-11-17 at 10 59 39 am" src="https://cloud.githubusercontent.com/assets/1784821/20377494/021557be-acb6-11e6-8464-7f5a47d0e121.png">

## Possible Solution

We can sort forms list on basis of `_give_set_price` ( in case of simple form) and  minimum amount level ( in case of multi donation form).

## Steps to Reproduce (for bugs)

1. Go to `Donations --> All Forms`
2. Sort list by `Amount`

**Comment by kevinwhoffman** [comment]
Sorting this column is problematic for a few reasons:

1. **It's difficult to sort a multi-level range as a single field.** When sorting a range of values such as $5-$15, the upper limit is not being considered when sorting in reverse. Instead the value of the field is considered to be $5 (the lower limit) at all times.
2. **Custom amounts add confusion.** A form may have multi-level donations set at $5-15 but it also accepts custom amounts as low as $3. This means the actual range of acceptable amounts is $3-Infinity since there is no maximum limit set for the custom amount. Indicating the amount as $5-15 when the actual acceptable amount is $3-Infinity is misleading.

**Comment by DevinWalker** [comment]
The issue right now the column is sortable, but it doesn't sort in order. As a user, I just want it to sort more logically or not sort at all. 

1. It's still an improvement if we only sort by the minimum donation amount. You can easily scan the column and see the donation amounts line up logically since they are sorting by minimum each time. We can start here an iterate from this point as needed.
2. **Disregard custom amounts.** Perhaps we can have an custom amount indicator within the column, but I don't think the column data needs to change from $5 -15 to $3-infinity when custom amounts are accepted. That would likely confuse users who didn't know it was custom amount enabled.

**Comment by kevinwhoffman** [comment]
I agree the best path forward is to sort by minimum donation amount while disregarding custom amounts. This means we're really sorting by the minimum _set_ donation.

The issue is that we don't currently have a meta field that could be considered the minimum set donation for both single- and multi-level forms. One possibility that @mehul0810 suggested in Slack was to set `_give_set_price` equal to the lowest donation level for multi-level forms. Doing so would give us a single meta field that could be sorted in a straightforward manner.
