### ISSUE TITLE
Conflict between Related Posts plugin and Give

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/Give#129]
Hey guys

I posted about the conflict of Related Posts and Give at the support forum for Related Posts. 
https://wordpress.org/support/topic/related-posts-and-the-plugin-give?replies=2#post-6938838

Check the above link.

Have a great day!

**Comment by mathetos** [comment]
Interesting. We'll take a look for sure. Thanks for the heads up.

**Comment by DevinWalker** [comment]
Hmm, I understand why this is happening. We've also had some issues with Jetpack's social share's attaching onto the forms because we run the content through the_content filter. 

Proposed fixes:

1. Create an option to enable/disable the_content filter (disable by default)

2. Add a filter (no option) to enable it.

3. Just disable it (some users could want it)

**Comment by DevinWalker** [comment]
Hey I just fixed this by adding an option to choose whether you want to display content through the_content filter or not found under Give > Settings > Advanced > Filter Control - releasing in 0.9.5 - thanks Paal.
