### ISSUE TITLE
Refactor Core Email Settings

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1346]
## Issue Overview
@ravinderk and I discussed revamping Give's email functionality so that it is more flexible and easy to work with.

![image](https://cloud.githubusercontent.com/assets/1571635/21254720/061bb1c4-c31c-11e6-83b6-ed73b1dba569.png)

**Related Issues** 
#1215
#1030
#611
#1607
#1623

**Comment by mathetos** [comment]
WOOT! +1000 on this!!

👍 👍 👍 👍 👍

**Comment by kevinwhoffman** [comment]
This will be really helpful to have all email settings accessible from one place. Here are a couple suggestions.

![1346-email-notifications-feedback](https://cloud.githubusercontent.com/assets/1938671/21505722/f955bd5c-cc37-11e6-9523-63c19585ac0e.png)

See [WooCommerce example](https://docs.woocommerce.com/document/configuring-woocommerce-settings/#section-7). Table looks cleaner when descriptions are displayed in tooltips.

**Comment by DevinWalker** [comment]
I agree @kevinwhoffman - if we can also customize the cog icon so it's a button as well that would make it even cleaner:

![061bb1c4-c31c-11e6-83b6-ed73b1dba569](https://cloud.githubusercontent.com/assets/1571635/21505883/57e101aa-cc20-11e6-95ef-21ee834dd7c1.png)

**Comment by mathetos** [comment]
@DevinWalker Would love a button that says "Edit Email" instead of the cog.

**Comment by kevinwhoffman** [comment]
![image](https://cloud.githubusercontent.com/assets/1938671/21506106/ab4b58a2-cc3b-11e6-8483-deb311496adb.png)

Do you think it makes sense to stick closer to the WP Core UI, where hovering over the row displays links? I can see it being helpful to preview the email directly from this screen, rather than having to click into settings and scroll down to find the preview button.

**Comment by mathetos** [comment]
Hmmm.... I like that idea. Here's all the ideas all in one:

![image](https://cloud.githubusercontent.com/assets/930724/21506541/be0da62c-cc25-11e6-9ad4-b5c30d6d5b0d.png)

1. The checkmark enables/disables the email dynamically without a page refresh
2. Hovering over the title shows the "Edit | Preview" links
3. Clicking the "Preview" link opens the email in a modal -- no page refresh
4. Recipient can be changed directly, and {tags} can be used. This would update similar to how QuickEdit works in WordPress Core on Pages/Posts
5. I think having the additional "Edit Email" button at the end is just helpful since the "Edit" is hidden by default until hovering.

**Comment by DevinWalker** [comment]
Nice feedback and revisions.

1. Yes
2. Yes
3. Yes
4. This will just open a new window like it does for now. We can update it to open a modal later.
5. I don't like this option so much. It looks like our shortcode's click-to-copy field and people aren't really going to be changing the recipients very often so there's not really a need to quick edit. 
6. I like using an icon rather than text

**Comment by ravinderk** [comment]
@DevinWalker I showed description under title because we are following the same pattern for core setting. Let me know if you still want to change them

<img width="1021" alt="screen shot 2016-12-28 at 3 43 10 pm" src="https://cloud.githubusercontent.com/assets/1784821/21519613/a2d51cec-cd14-11e6-9276-b170d3860063.png">

**Comment by DevinWalker** [comment]
@ravinderk for the new email settings it looks better to use tooltips for the descriptions. It just looks a lot better when it's in a table.

**Comment by ravinderk** [comment]
@DevinWalker Alright. I will update UI as suggested.
