### ISSUE TITLE
'Donation Receipt' is not an accurate heading for a pending or offline donation

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1396]
## Issue Overview

When a donor fills out the form for an offline donation, the donation receipt page should not say "Donation receipt"

## Expected Behavior
Instead it should perhaps say something like "Offline Donation Entered" or something like "acknowledgement" or other terminology. 

## Possible Solution
You could either make that text filterable at https://github.com/WordImpress/Give/blob/master/includes/admin/shortcodes/shortcode-give-receipt.php#L27 or have a check for offline that generates a different title there.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mathetos** [comment]
This seems related to this issue we pushed out in 1.7:
https://github.com/WordImpress/Give/issues/509

But maybe instead of the Status notification at the top, it simply outputs the Offline Donations Instructions and no receipt table at all. The title would then be "Your Donation is Almost Complete!"
