### ISSUE TITLE
Accessing Goals from the API

### ISSUE THREAD

**Issue by jam3sn** [WordImpress/Give#1423]
Hi There, 

I was wondering if you'd be able to add Goals to the Form API. It has donations which is great but I'd love to be able to access the Goals in this too?

I saw your response here: https://wordpress.org/support/topic/give-api-donation-form-goal-retrieve/ not my original question but didn't see him add it to the issues.

Thanks!

**Comment by DevinWalker** [comment]
@mehul0810 for this one please ensure that goals are accessible via:
1. Stats endpoint
2. Donation forms endpoint

**Comment by mehul0810** [comment]
@DevinWalker @ravinderk I've created few snapshots for integrating Goals in Stats as well as Donation Forms API Endpoint. The Snapshots attached will provide a basic idea how it will look with goals integrated in the api endpoints

**For Stats API Endpoint**
![goals_with_stats_api_endpoint](https://user-images.githubusercontent.com/1852711/26931486-4ef0c61e-4c7e-11e7-9d5a-beef05c0ab78.png)

**For Donation Forms API Endpoint**
![goals_with_donations_endpoint](https://user-images.githubusercontent.com/1852711/26931503-5b663f82-4c7e-11e7-84fb-28129f75ef84.png)

Please check and let me know your thoughts on it so that we can integrate the best possible solution for this.

**Comment by DevinWalker** [comment]
@mehul0810 the `stats` api endpoint should not have `goals` wrapping the entire output. It should appear as the `forms` API endpoint does as another item in the list. Also it should be `goal` not `goals` as there's only _one_ goal you can set per form.
