### ISSUE TITLE
Reporting "Last Year" filter shows December donations on wrong vertical Axis

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1428]
## Issue Overview

When using the "Last Year" filter on our Give Reports chart, it shows the December Donation totals on the January THIS YEAR axis incorrectly.

## Expected Behavior
The January THIS YEAR shouldn't appear at all, and the December donations should be on the December vertical axis.

## Current Behavior
You can see the issue here in Version 1.7.2
![reporting-last-year-month-off](https://cloud.githubusercontent.com/assets/930724/22439932/515cc298-e6e6-11e6-9334-56fb0ab848a8.png)

Here's what it looks like in Give 1.8:

![image](https://cloud.githubusercontent.com/assets/930724/22439978/87ebbcd8-e6e6-11e6-9e64-5b3154950a19.png)

So there's a minor improvement in that the January 2017 vertical axis is listed, but it shouldn't be there at all, and the donations should be on the December 2016 axis instead.

## Steps to Reproduce (for bugs)
1. Have a bunch of donations in November 2016, December 2016, and January 2017
2. Go to "Donations > Reports"
3. Change the filter to "Last Year"
4. You'll see that the December donations axis is empty and instead the January axis shows the amount for December.

**Comment by ravinderk** [comment]
@DevinWalker We can set pointer on day one of last month like Dec by fixing this code.
https://github.com/WordImpress/Give/blob/master/includes/admin/reporting/graphing.php#L154

but I also find that when we will generate custom report then our logic totally neglecting date for selected month means if I chose date Jan 1, 2017, to Feb 7, 2017, after making a new donation on Feb 7 then report will always show new donation in report because we are calculating donation for whole month even if admin provide specific date.

<img width="1064" alt="screen shot 2017-02-07 at 4 18 39 pm" src="https://cloud.githubusercontent.com/assets/1784821/22688348/d9f5df88-ed51-11e6-821a-7e28c75d5149.png">

**Comment by DevinWalker** [comment]
@ravinderk thank you for the explanation. Please provide a recommended solution to resolve.

**Comment by DevinWalker** [comment]
I just investigated and the data we are providing to jquery plot seems to be good. However, the plugin I believe is responsible for it causing this issue. See: https://github.com/flot/flot/issues/1291

EDD has the same issue. We should rather focus our efforts on #1114 and revamp the reports. Therefore, I'm closing until we reach that point.

**Comment by mathetos** [comment]
@DevinWalker I'm confused though because #1114 is also closed. Are you creating a new issue or Epic for the Report charts?

**Comment by DevinWalker** [comment]
@mathetos sorry I linked to the wrong issue. Here it is: https://github.com/WordImpress/Give/issues/1527
