### ISSUE TITLE
Allow for basic html tags in multi-level buttons (safely)

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1469]
## Issue Overview

Let's allow basic html tags to be inserted into multi-level labels. But only for buttons and radio buttons, since they would break a dropdown.

## Current Behavior
Currently we're stripping all tags from the multi-level labels

## Expected Result of this implementation
Users occasionally want to style these buttons. This request for example only requires a `<span>` element in the labels.
https://wordpress.org/support/topic/change-multilevel-button-styles/#post-8786856

## Todos
- [ ] Implement
- [ ] Test with lots of different valid html elements
- [ ] Test with broken html to see what we can do about that
- [ ] Update Documentation

**Comment by kevinwhoffman** [comment]
@mathetos I was able to generate the same markup as your jQuery solution using the [`give_form_level_text`](https://github.com/WordImpress/Give/blob/master/includes/forms/template.php#L505) filter.

```
add_filter( 'give_form_level_text', 'prefix_customize_give_buttons', 10, 3 );
function prefix_customize_give_buttons( $level_text, $form_id, $price ) {
	return '<span>' . $price['_give_amount'] . '</span>' . $level_text;
}
```

There are a few reasons why I think this should be solved by the existing filter instead of allowing HTML in the input fields.

- Keeps markup out of editor, generally a best practice and less prone to breakage by the user.
- User does not have to repeat the markup or remember the exact syntax when editing a level. Consider a site with many forms that all want to use the same button styles.
- Parsing a value from the `Amount` field would be difficult if we allowed markup.
- Provides more flexibility for developers or theme authors who want to style Give buttons without the user having to worry about markup.
- Keeps UI clean.
- Customers requesting this feature are likely comfortable with code since they are requesting to enter markup, so implementing a filter snippet should be feasible for them.
