### ISSUE TITLE
Button display mode should have attribute for Button Text

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1494]
## Issue Overview
Give 1.8 introduced "Button Mode" to our display methods. We need to add an option in the shortcode builder and widget to define what the button text is.

**Comment by DevinWalker** [comment]
@ravinderk two items remaining here:

## 1. Conditional formatting:
![2017-03-03_10-20-01](https://cloud.githubusercontent.com/assets/1571635/23563316/02d04cf2-fffb-11e6-83d4-e30c1914cba8.png)

This field needs to conditional based on the selected "Donation Option" field value. If the field value is anything other than "All Fields" it will display. Otherwise, it is hidden and is hidden by default. This is because the field is not 

## 2. Add Field to Widget
![2017-03-03_11-07-02](https://cloud.githubusercontent.com/assets/1571635/23565262/b1425bc6-0001-11e7-80d7-8ff4f56207be.png)

The widget needs to have this conditional field as well.
