### ISSUE TITLE
Better way to notify user about updates and upgrades

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1538]
## Issue Overview

In some cases, admin notices can be disabled on the website, so the user will not get the important upgrade or update notices.

To make sure user will get these notifications, we can create a conditional update admin page which will appear in plugin menu if current version has any update or upgrades. By this way, the user can read all notices and take the required action.

<img width="951" alt="screen shot 2017-02-23 at 12 48 08 pm" src="https://cloud.githubusercontent.com/assets/1784821/23248885/a1dc409c-f9c7-11e6-9061-c03af914e4fc.png">

## Todos
- [x] Update admin page related wireframe
- [x] Development
- [x] Test
- [ ] Documentation

**Comment by mathetos** [comment]
I LOVE this idea! My only hesitation is giving it it's own sub-menu item. I think I'd prefer that it's a tab in the TOOLS menu, then that "2" could show up next to TOOLS, and when they click on it, they'd see the "Updates (2)" tab with the "2" in there as well.

**Comment by ravinderk** [comment]
@mathetos I added `Updates (2)` to the menu because this will conditionally appear in menu list if there are any update.

@DevinWalker What do you think?

**Comment by kevinwhoffman** [comment]
Great idea. Here's my recommended flow:

### 1. Log in and see badge next to Give menu item.

This gets user's attention and alerts them to Give-related updates from anywhere in WP admin without being obtrusive.

![give-1538-updates-collapsed](https://cloud.githubusercontent.com/assets/1938671/23276860/e3289ca0-f9d9-11e6-9e14-94f2fd8c40d5.jpg)

### 2. Expand the Give menu item to reveal Updates submenu item with badge.

![give-1538-updates-expanded](https://cloud.githubusercontent.com/assets/1938671/23276869/e84e47a2-f9d9-11e6-918a-bbec686fe700.jpg)

### 3. Click Updates and land on the Plugins page with prepopulated "give" query.

![image](https://cloud.githubusercontent.com/assets/1938671/23277048/80bafa26-f9da-11e6-8584-8b20fc095dfa.png)

`http://example.com/wp-admin/plugins.php?s=give`

When I read @ravinderk's proposal, my first question was how would the updates take place and what would that look like? I think step 3 in the user flow above is a simple, elegant way to show the user updates related to Give Core and Give Add-ons while leveraging the plugin update functionality that already exists. This way there is no need for a special Give updates page.

Ideally step 3 would lead only show Give plugins that have an update available, but in my brief testing it appears the "give" search query overrides any status parameters.

Also note the colors and behavior described above are in line with how Core handles badges.

**Comment by DevinWalker** [comment]
## Updates Screen Overview

@kevinwhoffman points 1-2 are how @ravinderk and myself envisioned it.  However, the issue with the `1.8` release was that some users didn't ever see the _database_ upgrade that was requiring their action. This can be due to a variety of reasons, either a plugin is blocking it from displaying such as "WP notification center" or they simply are ignoring all the notices which is actually pretty common. 

Having our own "Updates" conditional screen would be dual purpose. It would serve for both plugin updates and database upgrades requiring their action. 

## Conditional "Updates" Screen Wireframe

![updates-screen](https://cloud.githubusercontent.com/assets/1571635/23278471/892c3cd8-f9c6-11e6-956b-a68a236528e0.png)

Clicking "Update Now" for a database update would go to the database update screen. Clicking it for a plugin update could then go to WP's plugin update screen like @kevinwhoffman outlined above.

**Objectives**
1. Make updating more clear and easy
2. Doesn't solely reply on WP notifications
3. Reenforces the need to have a _valid_ and _active_ license key for Add-ons
4. Reenforces the need to create a backup prior to _any_ update

**Comment by mathetos** [comment]
@DevinWalker Do you imagine the "Updates" menu item only appearing when/if an update is available? I'd prefer it not be there if it's not necessary.

**Comment by DevinWalker** [comment]
@mathetos yes

**Comment by kevinwhoffman** [comment]
I came across this in ACF Pro when the plugin needs updated. The Update Plugin button links to the Plugins page with a prepopulated search query so that only ACF Pro displays. I described something similar where we would prepopulate a "give" search query so only Give core and add-ons would display.

I also thought the changelog was a nice touch.

![image](https://cloud.githubusercontent.com/assets/1938671/23867467/5c31a0e4-07f2-11e7-947a-3eebed083620.png)

**Comment by mathetos** [comment]
Just additional info to consider. I had a user who couldn't update since Give version 1.7.2 because he kept getting the "Give needs to update..." alert, and when he clicked on it, it would log him out, then he'd see the "Give needs to complete a database upgrade..." message and that would log him out also.

Turned out that the admin redirect URL was being generated without "www" in it, so the update process never resumed no matter how many times he logged back in.

Just info to keep in mind.
