### ISSUE TITLE
WYSIWYG doesn't currenlty render oEmbeds

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1545]
@mathetos commented on [Wed Feb 22 2017](https://github.com/WordImpress/Give-Form-Countdown/issues/17)

This might be a Give CORE issue, but if you add a YouTube video into the "Duration Ended Message" WYSIWYG field, it will render as an oEmbed in the backend, but not in the front-end.

**Comment by mathetos** [comment]
Steps to Reproduce:
1) Test with our new Give Form Countdown Addon
2) In the "Duration Achieved Message" field, enter a Youtube link
3) Set the form to expire in the past
4) Save and view the form and instead of a rendered youtube video, you'll just see the youtube link output onto the page

In testing this I believe this has to do with how our WYSIWYG field is saving the data.

**Comment by ravinderk** [comment]
@mathetos oEmbeds is not working in goal message because it should be a plain text in terms of current core goal message design. Since we updated goal message field to `WYSIWYG`, so core goal message design will break if anybody uses anything other then text.


For now you can use `give_goal_closed_output` filter to render oEmbeds.
```
function give_custom_goal_message( $styled_goal_message, $form_id ) {
	$goal_message = apply_filters(
		'the_content',
		get_post_meta( $form_id, '_give_form_goal_achieved_message', true )
	);

	return $goal_message;
}
add_filter( 'give_goal_closed_output', 'give_custom_goal_message', 10, 2 );
```

For Ref: https://github.com/WordImpress/Give/blob/release/1.8.3/includes/admin/forms/class-metabox-form-data.php#L397#L404

**Comment by mathetos** [comment]
@ravinderk Thanks for the clarification. I do think it's important that a WYSIWYG field outputs exactly as it does in the admin -- currently the oEmbed renders in the Admin. That is the expectation users will have as well.

**Comment by DevinWalker** [comment]
@mathetos me too, I have a fix coming for that in 2 min.
