### ISSUE TITLE
{fullname} email tag is broken with two-word first names and blank last name

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1585]
## Issue Overview

the {fullname} email tag is not behaving as expected with two-word first names and a blank last name.

## Expected Behavior
It should display just the first name in this scenario:

![screen shot 2017-03-16 at 4 37 46 pm](https://cloud.githubusercontent.com/assets/9629102/24017573/f848b5aa-0a66-11e7-9479-f7a28c5ad6b6.png)

## Current Behavior

GIven the above "first name" the {fullname} tag is returning "Ben's Automotive Automotive"

## Steps to Reproduce (for bugs)

1. create an email template or pdf receipt template with the {fullname} tag
2. submit a donation with a two-word first name and a blank last name
3. view the email that results, or the pdf receipt.

## Todos
- [ ] Tests

**Comment by kevinwhoffman** [comment]
I looked into this and found the `{fullname}` email tag is working correctly insofar as it accurately reflects the name in the database. The problem lies in the way first name and last name are combined when a customer is created.

The `wp_give_customers` table uses a single column for name, and `explode()` is used in multiple places throughout the plugin to determine first and last name. `explode()` uses a space delimiter and assumes the second item in the array is the last name, which is causing the duplication described in the issue.

Here is one such example: https://github.com/WordImpress/Give/blob/master/includes/payments/class-give-payment.php#L2091-L2092

## Recommended Solution

First name and last name should have separate columns in the customers table. Otherwise we can never guarantee where the divide between first and last occurs.

While the issue doesn't appear to show up in the admin interface, the issue does appear in the email tag and would also be visible in data returned by the Give API.

@Benunc @mathetos @DevinWalker Can you rename the issue for clarity?
