### ISSUE TITLE
Enhancing Disconnect User feature on Donor Single View in admin

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#1720]
## Issue Overview
There is an option to disconnect user from donor. But, in case, if admin has mistakenly disconnected user from donor then there is no option to reconnect user as well as there should be a confirmation popup on click of disconnect user.

## Expected Behavior

On clicking `Disconnect User` should have a confirmation popup before disconnecting user which will have an additional data validation to make sure that admin is intentionally disconnecting user from donor.
![confirm_disconnection_user_from_donor](https://cloud.githubusercontent.com/assets/1852711/26315100/aab5b918-3f2d-11e7-99e3-e828f1681cf7.png)

After successfully disconnecting user from donor, this is how it should look as below and on clicking `Reconnect Now` will reconnect user to donor which was connected earlier.
![reconnect_user](https://cloud.githubusercontent.com/assets/1852711/26315219/08bd5818-3f2e-11e7-9ed8-eeb2d838601b.png)

## Possible Solution
To implement reconnection of user, we need to store the user id to customer meta (i.e. donor meta) and customer id (i.e. donor id) to user meta. 

## Steps to Reproduce (for bugs)
1. Go to Donations > Donors
2. Click on any existing donor

## Related Issues and/or PRs
#1206 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
I agree there should be a confirmation for the disconnect. However, I don't think there needs to be the option to reconnect because current reconnecting is this simple:

![2017-05-25_12-45-13](https://cloud.githubusercontent.com/assets/1571635/26467600/323eea8c-4148-11e7-9749-be5f6edb7574.gif)

I have modified https://github.com/WordImpress/Give/pull/1727/ to only include the JS confirmation and moved this to 1.8.8 release. Note: in 2.1 we will be doing a full revamp of the donor's profile page.
