### ISSUE TITLE
Fail gracefully with unsupported PHP versions.

### ISSUE THREAD

**Issue by tw2113** [WordImpress/Give#1723]
## Issue Overview
When activating the plugin on a non-supported version, their is an error at the top of the plugins page that does not whitescreen the site thankfully, but does offer potential confusion to the user who may not know how to understand php errors.

## Expected Behavior
Provide some sort of admin notice or similar outlining the fact that the user is on an unsupported version of PHP and they should talk to a developer or their host about upgrading.

## Possible Solution
Generic admin notice and prevent the loading of the rest of the plugin.

Implement https://github.com/Yoast/whip

**Comment by DevinWalker** [comment]
@tw2113 can you tell me which version of PHP you tested with and what the php errors said?

**Comment by tw2113** [comment]
5.2.17

This error both when trying to activate and also just loading the site when downgraded to an unsupported version:

Parse error: syntax error, unexpected T_STATIC in /app/public/wp-content/plugins/Give/includes/class-give-cache.php on line 46

**Comment by mehul0810** [comment]
@DevinWalker @ravinderk I've analysed this issue and the plugin fails on activation with error that is generated due to `static` keyword not supporting PHP versions < 5.3.

We can show notice for PHP versions < 5.3 using `WHIP by Yoast` to overcome this issue rather than showing error as suggested by @tw2113.

Let me know your thoughts.
