### ISSUE TITLE
Test Mode Admin Notification Improvements

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#174]
Instead of an annoying notification like we have now, we should rather do what Coming Soon does: 
![7-15-2015 8-21-11 pm](https://cloud.githubusercontent.com/assets/1571635/8714885/36b9775c-2b2f-11e5-9c42-c28b72dc5311.png)

Why? 

1. The notification as it is now acts strange with tabs: ![7-15-2015 8-23-15 pm](https://cloud.githubusercontent.com/assets/1571635/8714897/5a7e6a1c-2b2f-11e5-8b77-a3b8d2672143.png)

2. It also has a close button that doesn't actually work. WordPress has added this in 4.2 automatically to notices - but we don't respect the actual close for this notification.

3. It's more noticeable and less intrusive to the UX

**Comment by DevinWalker** [comment]
@mathetos do you think our notification can be green? I feel that's just as noticeable and not as alarming as red.

**Comment by mathetos** [comment]
I'm not sure that alert is best for this purpose. That puts the alert EVERYWHERE in the backend instead of just on the Give Admin pages. I agree that the current alert is a little awkward with the tabs, but I think adding TItles above the tabs could improve all those pages and the alert could be positioned above the tabs below the page title.

We'll just have to chat more about it. Totally agree that making it VERY obvious that Give is in Test Mode is really important.

**Comment by DevinWalker** [comment]
I think it's a good thing it's everywhere. User's won't forget it's in Test Mode prior to launch, etc.

**Comment by DevinWalker** [comment]
Working a lot with Give with Test Mode enabled makes the notice really annoying now.

**Comment by DevinWalker** [comment]
Let me know what you think of it now

**Comment by DevinWalker** [comment]
This is incorporated now
