### ISSUE TITLE
Add email access token logic to "View In Browser" link in Donation Receipt email

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1790]
## Issue Overview
Currently, the "view in browser" link in a donation confirmation email will only work if the link opens in a browser where the transaction just took place, because the session is still active. 

## Expected Behavior
The "View In Browser" link should create a session in the same way an email access token does. That way, no matter where the donor clicks that link (on a different device, using a different browser, etc), they will have access to the donation receipt and other associated donor account information.

## Current Behavior
Site is set up _without_ email access, and no login is required to donate (on a one-time donation).

Donor submits a one-time donation on his laptop, but does not immediately check his email. Later, on his phone, he clicks the "view receipt in browser" link. 

He's greeted with this confusing box: 
<img width="740" alt="screen shot 2017-06-21 at 3 02 04 pm" src="https://user-images.githubusercontent.com/9629102/27402459-afb51f66-5694-11e7-830d-2ab0fd9d89e0.png">

He doesn't have a login. So he's stuck.

## Possible Solution
Since we already know the user has access to the email account (where he clicked the link), it would make sense to add some of the verified token logic from our email access class to that link. That way, no matter what device he's on, the donor can see his donation receipt and history.

This is what is added in our email access class once the token has been verified:
```
add_filter( 'give_can_view_receipt', '__return_true' );
add_filter( 'give_user_pending_verification', '__return_false' );
add_filter( 'give_get_users_donations_args', array( $this, 'users_donations_args' ) );
```
This line is here: https://github.com/WordImpress/Give/blob/master/includes/class-give-email-access.php#L142

## Steps to Reproduce (for bugs)
1. Email access disabled.
2. One time donation form where guest donations are accepted, and no login/register fields shown.
3. Email receipt includes the {receipt_link} tag.
3. Submit donation.
4. Follow link in email, but make sure to open the link in a different browser than the transaction took place in.

You'll get the box above.

Even with Email access enabled, you'll still get a confusing "put in your email" form, and that seems unnecessary because we already know they have access to that email. They clicked a link in it.

## Todos
- [ ] Tests
- [ ] Update Documentation

**Comment by ravinderk** [comment]
@Benunc Make sense. I will think about it how we can make donor experience better with donor reciepts and Let you know.

**Comment by mehul0810** [comment]
@ravinderk @DevinWalker I've added some of my findings and suggestions after testing as per our discussion over call today.

### Some Findings
- When Guest Donation is enabled, then Email Access should get enabled otherwise it will ask for login when a `View it in browser` link is clicked.
- When Guest Donation is disabled, then Email should get disabled otherwise it will create a non secure environment where admin doesn't want the donation receipts shown to anonymous user.
- If `email access` is `enabled` and then proceed with transaction of any form. You'll receive an email containing `View it in browser`, click on it. It will ask for email to enter. Then I've entered a different email from which i did the transaction and it is showing me the donations list of the email which i entered. This seems to be a weird case. This same case is for No Login.
- If `email access` is `disabled` and then proceed with transaction of any form. You'll receive an email containing `View it in browser`, click on it. then you'll be redirected to the payment receipt, if you're using the same browser session with which you have made the transaction. If you check the same in incognito mode then it will ask for login which you won't be having in case of forms not asking for login or registration.

### Suggestions
- On installing Give, default option for `Email Access` should be `enabled` as per the discussion with @DevinWalker and @ravinderk over call.
- On using login or registration option with Guest Checkout disabled then the Email Access should get disabled as well.
- Need improvement in the `View it in browser` link, where we will add access token as a query parameter with the link and then when opening that link, we'll verify that the access token created is for specific email. If verified, then user will be able to access the receipt without additional step of sending access token and verifying the email again.

**Comment by DevinWalker** [comment]
## Response

**1.** Ensure the `Email Access` is `enabled` for all new installs by default

**2.**
 > On using login or registration option with Guest Checkout disabled then the Email Access should get disabled as well.

Disagree, leave it enabled. Email Access only applies to after the donation to retrieve donation records and manage subscriptions, etc. This should be easily accessible still.

**3.** 
> Need improvement in the View it in browser link, where we will add access token as a query parameter with the link and then when opening that link, we'll verify that the access token created is for specific email. If verified, then user will be able to access the receipt without additional step of sending access token and verifying the email again.

Agreed. This is the underlying issue we're trying to address here. Please resolve this as you describe.

**Comment by raftaar1191** [comment]
Getting noticed:

![image](https://user-images.githubusercontent.com/22215595/32050344-123fe110-ba6e-11e7-885f-8838de09dbf8.png)

**Comment by ravinderk** [comment]
@raftaar1191 Issue has been fixed. Please review again.

**Comment by raftaar1191** [comment]
Checking @ravinderk

**Comment by raftaar1191** [comment]
Checking and updating in the sheet @ravinderk 

Thanks @mehul0810 for the PR
