### ISSUE TITLE
When period used as thousands separator, the total is wrong and minimum amount alert triggers

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1849]
## Issue Overview
When period used as thousands separator, the total is wrong and minimum amount alert triggers

## Current Behavior
Some countries use a period as the thousands separator. Currently, when that is set it makes the total amount incorrect and triggers the minimum donation alert falsely.

## Expected Behavior
Periods should be supported as thousands separators correctly.

## Steps to Reproduce (for bugs)
1. Go to "Donations > Settings > General > Currency" and set the thousands separator to a period (.). The decimal seperator and the number of decimals won't matter.
2. On your form, set a minimum $20 donation.
3. Test a donation by donating over $1,000 (in order to trigger a thousand separator). The totla will be reflected as $1 instead of $1,000. You should then see a message like this:
![image](https://user-images.githubusercontent.com/930724/28082180-94499940-6626-11e7-871b-b5318e803a5a.png)

## Customers reporting this issue:
* https://secure.helpscout.net/conversation/391650991/8704/?folderId=672201
* https://secure.helpscout.net/conversation/398883082/8972/?folderId=672201

**Comment by DevinWalker** [comment]
It looks like `give_sanitize_amount()` is not properly sanitizing when the donation amount is more than $1000 and decimals are used for the thousands separator.

**Comment by mathetos** [comment]
As a reference, here's a list of currencies and their formatting:

http://www.thefinancials.com/Default.aspx?SubSectionID=curformat

**Comment by ravinderk** [comment]
@DevinWalker @mathetos @kevinwhoffman @mehul0810  Currently we are using `number_format` function for formatting number. It does not respect currency, that reason behind we do not have correct number formatting for `INR` currency. Same thing happens in Woocommerce (check screenshot).

<img width="504" alt="screen shot 2017-07-12 at 12 28 12 pm" src="https://user-images.githubusercontent.com/1784821/28106005-aa82e138-66ff-11e7-9599-b80b43d5cd69.png">


[Check Indian number system](https://en.wikipedia.org/wiki/Indian_numbering_system)

We currently have the options in core settings to set decimal, thousand separator, number of decimal for number formatting. I think it will be useful if number formatting becomes currency aware.

I found a library which does it. Let me know what do you guys think about this.
https://github.com/gerardojbaez/money

**Comment by ravinderk** [comment]
@DevinWalker @mathetos @kevinwhoffman @mehul0810 I reviewed my solution and I think we do not need this. I can achieve this just by simple code because except India most of the country has similar number system means separator changes but logic remain same.

**Comment by ravinderk** [comment]
@mathetos @DevinWalker This problem is a little bit complicated.

**Problem**
As @mathetos said some countries have decimal separator as thousand separators, we can fix this, but then the problem started occurring with database values because we are storing already sanitized values in the database.
for example, if we store `1` with `3` decimal precision then `1.000` will store in the database. If we format this value then it's value will become `1000`.
The reason behind this is we are imposing sanitization to each value even for database value which is already sanitized.
for ref:
https://github.com/WordImpress/Give/blob/master/includes/formatting.php#L145
https://github.com/WordImpress/Give/blob/master/includes/formatting.php#L210


**Solution**
To solve this problem we can take out `give_sanitize_amount` function from amount formatting function and let start use them where they need. We can handle this change in core but this will also affect all addons, but it will help us to solve future problems.
