### ISSUE TITLE
You have to click "Donate" twice for the modal to pop-up

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#186]
Currently, the modal pop-up doesn't trigger until the donation amount is updated. This means that users most often have to click outside the amount field before clicking Donate, or worse, they end up hitting the donate button twice. 

![click-twice-donate-button](https://cloud.githubusercontent.com/assets/930724/8860599/beb35208-3139-11e5-9897-2fbe37f903ad.gif)

**Comment by DevinWalker** [comment]
@mathetos that gif is next level stuff :+1:

**Comment by mathetos** [comment]
@DevinWalker I serve to please

**Comment by DevinWalker** [comment]
After testing for this issue it looks like the problem is that the "Updating price" text is pushing the button out of the way when you attempt to click on it. Hiding the text with CSS will work to prevent this from happening when you place the form in tight places:

`form[id*='give-form'] p.give-loading-text.give-updating-price-loader { display:none !important; }`
