### ISSUE TITLE
Consider ways to enable admins to customize all form labels and tooltips

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1953]
## Issue Overview
Users very often want to customize the text used on their Give forms. Most commonly they don't like the words "Card name" for the placeholder for the "Cardholder name". But requests come steadily and regularly for all kinds of changes. 

Typically we are providing this snippet for small on-off changes:
https://github.com/WordImpress/Give-Snippet-Library/blob/master/translation-snippets/simple-translation-snippet.php

## Possible ways to tackle this
1. Maybe we can just handle this directly in the form edit screen somehow
2. Maybe we need a "Tool" that will generate a .PO file dynamically
3. Maybe we just use our built-in filters

## Questions to consider
1. Should this just be a Core feature?
2. Should this be a free Add-on?

**Comment by kevinwhoffman** [comment]
### Current

We currently translate the string in the template where the label appears. This occurs at the time of rendering which makes it difficult to filter unless we provided a filter for every label, which is unrealistic.

```php
<label><?php esc_html_e( 'First Name', 'give' ); ?></label>
```

### Proposed

Instead we should reference the label text from an array of translated labels. By the time the label is displayed, the array has already been filtered with any customizations.

```php
<label><?php echo esc_html( $give_labels['first_name'] ); ?></label>
```

## User Customization

Users can customize the string values on a settings screen like this one.

![1953-settings-screen](https://user-images.githubusercontent.com/1938671/28953327-48ce9902-78a5-11e7-8040-047fda7d3836.png)

## Result

The default arrays would look something like this. We can either merge the user-defined values with these coded defaults, or set our own defaults in the database upon installation and just fetch the arrays as a Give setting.

```php
<?php
$give_labels = apply_filters(
	'give_labels',
	array(
		'first_name' => __( 'First Name', 'give' ),
		'last_name'  => __( 'Last Name', 'give' ),
		'email'      => __( 'Email Address', 'give' ),
	),
);

$give_tooltips = apply_filters(
	'give_tooltips',
	array(
		'first_name' => __( 'We will use this to personalize your account experience.', 'give' ),
		'last_name'  => __( 'We will use this as well to personalize your account experience.', 'give' ),
		'email'      => __( 'We will send the donation receipt to this address.', 'give' ),
	),
);
?>
```

## What to Avoid

We should avoid [solutions like these](https://github.com/WordImpress/Give-Snippet-Library/tree/master/translation-snippets) that involve filtering `gettext`  because functions such as `__()` are fired dozens if not hundreds of times on a page. We would be better off fetching the customized labels as a user-defined setting. If filtering is still required, it only happens once at the time in which the array is defined.

**Comment by Benunc** [comment]
Backward compatibility with our existing snippets is a concern here. LOTS of folks have used these snippets to customize text: https://github.com/WordImpress/Give-Snippet-Library/tree/master/translation-snippets

**Comment by kevinwhoffman** [comment]
What I'm proposing should have no effect on the existing snippets so long as the strings themselves do not change. `gettext` functions will fire in either case; I'm just suggesting that instead of filtering every call to `__()` we instead filter the array of strings once.

**Comment by DevinWalker** [comment]
Now that we have the API in place, we now have to implement it's usage within the plugin.

**Comment by ravinderk** [comment]
@mehul0810 Start this after we finish Form API integration with donation forms.

**Comment by DevinWalker** [comment]
Closing in favor of upcoming Form API epic which this functionality will be part of.
