### ISSUE TITLE
GIVE_SLUG define doesn't affect slug

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#199]
`define('GIVE_SLUG', 'donate'); ` should change the Archive page and single form url to use `/donate/` instead of `/donations/` but it doesn't seem to be working correctly. Tested with both Archives disabled and enabled. Reseaved permalinks several times.

**Comment by allegres** [comment]
I am also facing this problem right now. I have tried the "define('GIVE_SLUG', 'blabla')". But it didn't worked. I've seen a section in GiveWp official site like: 

> Please note that this will have no impact on the “Default” permalink style, but on all others it will appear like the above. Also note that after making this change, it’s best to refresh your permalinks to see the change affected.

But I don't know how to do refreshing my permalinks. Any help would be appreceiated. :))

**Comment by JoshuaHungDinh** [comment]
Hello @allegres, Im sorry to hear your are difficulties defining a new page slug. A simple method for refreshing your permalinks can be done through the Wordpress dashboard.  

1. From the navigation menu, click Settings > then select Permalinks.
2.  On the Permalinks page you will want to take notice of what setting you have selected, options are Plain, Day and name, Month and name, Numeric, Post name, Custom Structure. If you are using a Custom Structure copy and save it, so you can put it back later.
3. Select any permalink setting other than your currently saved structure and click the Save Changes button. 
4. Once updated, reselect your original setting and save changes once again. You are finished when you see the “Permalink structure updated” message again. Your site permalinks should now be working. You may have to clear your browser cache before testing in order to see the change.

If the problem persists I would suggest submitting a new bug report as this issue was closed in 2015.  Submitting a new bug report will also allow us to bring more of our developers attention to this specific issue. Thanks for reaching out!
