### ISSUE TITLE
Occational display issue when browser window is resized

### ISSUE THREAD

**Issue by gingerling** [WordImpress/Give#2000]
## Issue Overview

Sometimes when browser window is displayed the form creator page has odd display issues where the left half of the info is hidden below the menu tabs. I fist noticed in when doing the "side by side" page display option on my PC, but happens at other window sizes too. My PC isfedora linux, but may be similar in Windows.  Browser firefox.

![screenshot from 2017-08-18 18-42-59](https://user-images.githubusercontent.com/2853040/29470694-60c278ac-8445-11e7-8c9d-914281e21f85.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by kevinwhoffman** [comment]
Thanks @gingerling for reporting this. I was able to reproduce the display issue, and we will get this fixed in an upcoming release.

## Steps to Reproduce

1. Resize form edit screen to a width between `1026px` and `850px`.
2. View any repeater field such as Multi-Level Donations or Tributes.
3. Confirm the overflow shown in screenshots.

## Screenshots

![image](https://user-images.githubusercontent.com/1938671/29475000-04df28dc-842c-11e7-8c35-7ea49abf4ff7.png)

**Comment by gingerling** [comment]
Thanks, great

**Comment by gingerling** [comment]
thanks! :)
