### ISSUE TITLE
Create setting and form import/export tool

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2009]
## Issue Overview

It will be good if we create a tool to import/export core settings and form. It will help to quickly copy setting and form to another WordPress install.

**Note:** While creating this tool please check the possibility of the element in content for example if the content has an image then the image must download as media to WordPress.

**Comment by mathetos** [comment]
Love it. @ravinderk where/how do you see this being implemented? Would it be under "Donations > Tools?" Or "Donations > Settings > Advanced?"

This could be very useful for Support purposes as well, so it would be excellent to maybe reference this from the System Info tab as additional info that could be useful.

This is a separate issue, but I'd also like a per-form settings import/export option. This would allow us to get a simple .txt file with json formatting to import a form from a customer with its exact settings, rather than having to get admin credentials to troubleshoot. I'll make a separate issue about this idea and link here, but the functionality might be related.

**Comment by ravinderk** [comment]
Chat summery between me and Matt:

It is good to create import and export for core settings and form.

**Matt comment**

> Those are the obvious ones, though Donations also generate Forms, sometimes a Freelancer will have a particular type of form that they use for many clients, they can export just that form settings and import.
> Caldera does a really good job of this.
> Also for Support, he often just asks for the JSON Export of whatever form is giving you trouble... then he can troubleshoot based on that, rather than having access to your whole site.

**Comment by raftaar1191** [comment]
https://github.com/WordImpress/Give/issues/2168

**Comment by Benunc** [comment]
I'd like to put in a vote specifically for a Tributes settings exporter. Should I make that issue on that repo? From a support perspective, Tributes is _tough_. There are _so many options_ it's often difficult to just recreate a customer's setup.
