### ISSUE TITLE
epic(admin-plugins): combine activation notices into tabbed interface

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2056]
## User Story

As a new Give customer I expect a pleasing interface when multiple add-ons are activated.

## Expected Behavior
Notice display without annoying multiple notices adding to the clutter.

## Current Behavior
Each add-on has an individual notice and bombards the admins. In turn, it gives a bad first impression.

![2017-09-07_17-58-59](https://user-images.githubusercontent.com/1571635/30191550-50c6d1e4-93f6-11e7-8c0f-9f3629261153.png)

We should take note what other plugins like Woo and Jetpack are doing. Combing the notices into a single tabbed interface would look good. 

## Possible Solution
Provide a singular, pleasant, interface.

## Steps to Reproduce
1. Fresh install
2. Multiple add-ons installed
3. Activate them
4. See the clutter

**Comment by kevinwhoffman** [comment]
## Content Tab Layout
![give-activation-banner-welcome-v01](https://user-images.githubusercontent.com/1938671/30195241-41385808-9426-11e7-969c-54419365d65f.jpg)

The content tab layout would be used for the Welcome, Documentation, and Support tabs. Each tab includes:

- Heading
- Description
- Primary and optional secondary CTA buttons
- Decorative image aligned right

## Add-ons Tab Layout
![give-activation-banner-add-ons-v01](https://user-images.githubusercontent.com/1938671/30195242-41392da0-9426-11e7-85ed-6686f0fb4eb3.jpg)

The Add-ons tab would have a special layout that simply lays out the installed add-ons in a grid with relevant links below each add-on title.

- Add-on title
- Documentation link
- Settings link (if available)

## Installation Behavior

The scenarios below define the state of the tabs depending on how Give and its add-ons are activated.

- Give Core activated without add-ons
    - Welcome (selected)
    - Documentation
    - Support
- Give Core + Add-ons activated together
    - Welcome (selected)
    - Documentation
    - Support
    - Add-ons
- Add-ons activated*
    - Welcome
    - Documentation
    - Support
    - Add-ons (selected)

*In the event that only add-ons are activated with an existing Give installation, then the Add-ons tab would be selected because it is assumed the user has already seen the welcome screen.
