### ISSUE TITLE
Better handling of custom amount text sent to PayPal

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#2161]
## Issue Overview
If you create a set form, but allow custom amounts, and add custom text to the custom amount, that text is appended to the title, and is confusing on PayPal's side.

## Expected Behavior

![screen shot 2017-10-03 at 3 13 05 pm](https://user-images.githubusercontent.com/9629102/31144064-7c6032e4-a84d-11e7-9858-9edf48957029.png) In this example, taken from https://newlungsfor.me The text "Give another amount by typing it in the box above" should not show up at PayPal. But it does, appended to the title of the Form. 

## Current Behavior
The custom amount text is appended to the form title at the payment gateway. 

## Possible Solution
On a set donation form, with custom amounts enabled, the custom amount text should not show by default, either on the front end of the form, or on the donation title passed to the gateway. 

If the user chooses to customize it, that text should not be shown at the gateway, for any reason. 

On multilevel forms, it's a bit more intuitive, because they pick that level from a list, so it makes sense to show it at the gateway, but even then, I think appending the amount/level is superfluous. 

## Steps to Reproduce (for bugs)
1. create a set donation form, and enable custom amounts. 
2. customize the custom amount text.
3. Submit a donation to PayPal. 
4. The custom amount text is appended to the end of the donation title. 

## Related Issues and/or PRs
#2071 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by Benunc** [comment]
user following up on this.

**Comment by DevinWalker** [comment]
Hmm I thought we fixed this... need to verify so I'm putting it on the 1.8.15 release.

**Comment by DevinWalker** [comment]
## Resolution Overview

Here is how the payment descriptions are now being sent to PayPal and other gateways that use the  `give_payment_gateway_item_title()` function.

### Custom Amounts

Because of the problem described in this issue, we are no longer sending appending _any_ text to the donation form title if a custom amount donation is made. This is because the text is usually not helpful and can be confusing, as described above, and also if we simply send "Custom Amount" appended it's not easily translatable and provides little value. 

The donor can understand via PayPal's user interface that they have provided a custom amount:

![2017-11-18_11-05-19](https://user-images.githubusercontent.com/1571635/32983865-7736f3a8-cc50-11e7-9f2d-c76ada6d9304.gif)

This works the same for both single and multi-level forms.

### Multi-level forms WITH Level Text

If a form has multi-level fields WITH the text for the level title completed then the level text will be sent along with the title:

**Standard Transaction Screen:**
![2017-11-18_10-59-59](https://user-images.githubusercontent.com/1571635/32983810-bcdd3436-cc4f-11e7-8e1c-a803298685b4.png)

**Donation Screen:**
![2017-11-18_11-00-41](https://user-images.githubusercontent.com/1571635/32983815-ca443f0c-cc4f-11e7-92fc-95738cfa6b1f.png)

### Multi-level forms withOUT Level Text

Previously to this issue we would use a fallback of the level _amount_ ($25.00) and append that to the form title so it would appeal like _Save the Whales - $25.00_. This is not necessary because PayPal, and most offsite gateways, display the amount to pay in multiple places. Appending it made it appear in too many places and provided little value.

**Comment by Benunc** [comment]
For this issue, is it intended behavior to still append the custom label text for a set (non-multilevel) donation? The "Give another amount by typing it in the box" from the original issue, that is.

For example, the `{donation}` email tag will still get that text appended to it. 

I can create a different issue if needed, but wanted to check here first.
