### ISSUE TITLE
Inputs don't focus the cursor correctly on iPhone

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2239]
## Issue Overview
Customer reported this here:
https://secure.helpscout.net/conversation/455703472/11205?folderId=672194

Using in iPhone, while the form is open in a modal, touch into a text input and the cursor will jump down and outside of the input area. 

Can be tested live here:
http://php7.mattcromwell.com/donations/basic-donation-form/

## Expected Behavior
The cursor should always stay inside the input area.

## Current Behavior
The cursor jumps outside the input area when focused on with an iPhone (any browser). On the customer site it consistently jumped outside the input. But on the demo site above, it jumps outside only on the first few touches, but gets better unless the page is refreshed.

## Possible Solution
There seems to be some general discussion about this issue. Here's a few solutions:
https://github.com/ftlabs/fastclick/issues/338

This Magnific issue also seems relevant:
https://github.com/dimsemenov/Magnific-Popup/issues/505

## Steps to Reproduce (for bugs)
1. Load this page with an iPhone (any browser): http://php7.mattcromwell.com/donations/basic-donation-form/
2. Click the donate button to open the form in the modal
3. Click into any of the personal info fields
4. You'll see the cursor drop down and outside of the input area.

**Comment by mathetos** [comment]
This may need to be tested with all payment gateways and Form Field Manager as well.

**Comment by kevinwhoffman** [comment]
I made a [barebones example](https://codepen.io/KevinWHoffman/full/VMoQgB/) on CodePen to isolate Magnific. I was unable to recreate the issue.

One thing I noticed is that the problematic Give forms seem to zoom in when the first input is focused. When this zoom occurs, that's when the cursor jumps out of the input field. Research shows that iOS will zoom in on an input if its font-size is less than 16px, but it's not clear to me if that is related to this bug since the problem only occurs in modals.

**Comment by ravinderk** [comment]
@kevinwhoffman @mathetos @DevinWalker 
Donate now and amount field border creates thin border on there joint which is not looking good.

**Original:**
<img width="1103" alt="screen shot 2017-10-27 at 9 44 01 am" src="https://user-images.githubusercontent.com/1784821/32087724-7eae08f8-bafb-11e7-9a93-ed6bb86c6013.png">

**After removing right border from amount field:**
<img width="1027" alt="screen shot 2017-10-27 at 9 45 14 am" src="https://user-images.githubusercontent.com/1784821/32087731-8e3836c2-bafb-11e7-861a-0793232ebc39.png">

Let me know if you guys wants to create issue for that

**Comment by DevinWalker** [comment]
I've looked into this and can't find a solution currently. I will continue debugging but for now I have to bump this to `1.8.17` and release `1.8.16` with other important fixes that shouldn't be held up.

**Comment by Benunc** [comment]
ANother customer report of this today. tagged `iphone-bug` in Helpscout.

**Comment by DevinWalker** [comment]
I've determined that this is a known issue with WebKit:

https://bugs.webkit.org/show_bug.cgi?id=176896

"Jon Lee" says:

> We haven't forgotten about this. We are aware this is an important issue and are looking into it.

Apparently the problem is present on major sites like Sony Playstation and others.

I attempted various fixes and workarounds and none work up to expectations because you can still get the cursor outside the field if you play around with it enough:

https://stackoverflow.com/questions/46567233/how-to-fix-the-ios-11-input-element-in-fixed-modals-bug
https://hackernoon.com/how-to-fix-the-ios-11-input-element-in-fixed-modals-bug-aaf66c7ba3f8

Other places that this bug has been detected and determined to wait for the fix:

https://github.com/vuejs/vue/issues/5544
https://github.com/18F/web-design-standards/issues/277
 
Another related bug is that when scrolling the blinking cursor doesn't move along with the content: https://bugs.webkit.org/show_bug.cgi?id=138201

**Comment by mathetos** [comment]
@DevinWalker Thanks for digging into this so deeply. I notified the relevant customers of your findings.

**Comment by dlinsen** [comment]
Still experiencing this issue on iphone 11 safari.
