### ISSUE TITLE
feat(form): allow forms to be queried based on close status

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2250]
## Issue Overview
Occasionally, users want to have an archive of Give forms, but exclude those that are closed because they achieved their goal. We currently have `post_meta` called `_give_close_form_when_goal_achieved` which returns just `enabled|disabled`, but when the goal is actually achieved and the form is closed, there's no way to query and exclude those forms. Adding `_give_form_is_closed` with `true|false` would benefit these users greatly.

**Comment by raftaar1191** [comment]
This issues had a [PR ](https://github.com/WordImpress/Give/pull/2756)

Kindly read this [comment](https://github.com/WordImpress/Give/pull/2756#issuecomment-363486559) on the PR for more information on how and when this PR is going to get merge

**Comment by DevinWalker** [comment]
Rethinking this one through... wouldn't it be better to have function like: `give_is_form_closed( $form_id )` which checks:

1. If goal is enabled 
2. If the option to close a form upon reaching goal is set
3. If goal the goal has been reached.

Then returns `true`. If false, it returns `false`. The downside of this would be multiple queries compared to a single meta query. What do you think?

**Comment by Benunc** [comment]
There are still users waiting for a fix for this issue, so I'm labeling it in the hopes that Devin's comment on the 6th of March led to another issue that actually resolves this.

**Comment by kevinwhoffman** [comment]
I'm putting this in 2.1 as I think it will become more requrested when we introduce the form grid shortcode.

> Rethinking this one through... wouldn't it be better to have function like: give_is_form_closed( $form_id ) which checks:
>
> If goal is enabled
> If the option to close a form upon reaching goal is set
> If goal the goal has been reached.

@DevinWalker We already have [`is_close_donation_form()`](https://github.com/WordImpress/Give/blob/ff6d80308e6d002c5541a74c41ae5d11ff892774/includes/class-give-donate-form.php#L1105-L1151) which does what you describe, but I don't think we want to run that against every form to determine if it is open or not. It also wouldn't work correctly with pagination if we are running checks after the query.

## Recommended Solution

What we need is a way to query only forms that are published and open, the most appropriate and performant solution is to add a custom post status called `Published (Closed)` which is assigned once a form meets its goal. 

![image](https://user-images.githubusercontent.com/1938671/38524454-a39454c2-3c1c-11e8-9b3e-20b2afc1504e.png)

![image](https://user-images.githubusercontent.com/1938671/38524501-c8c68292-3c1c-11e8-9e1c-36ae7eec601a.png)

We can hook into the completed donation and check to see if the form should be closed at that point. That way the calculation occurs after the donation rather than during each query in the archive.

## [give_form_grid] attribute

If we like the custom status approach, we should also add a `status` attribute to the `[give_form_grid]` shortcode so that only open forms can be displayed in the grid.

**Comment by kevinwhoffman** [comment]
**Call Summary**

**Participants**: @DevinWalker @mathetos @kevinwhoffman
**Topic**: Best way to query forms by closed status
**Result**: We agree to move forward with the recommend solution in https://github.com/WordImpress/Give/issues/2250#issuecomment-379903989. See the tasks below for next steps.

@mehul0810 I'm assigning this one to you. Please review the tasks and let me know if you're clear.

- [ ] Register custom post status for donation forms:
    - status: `publish_closed`    
    - label: `Published (Closed)` 
- [ ] Hook into completed donations to check if a goal is enabled and complete. If so, then switch the post status from `publish` to `publish_closed`.
- [ ] Write an upgrade routine for 2.1 that loops through all forms and sets the appropriate post status.

**Comment by mehul0810** [comment]
@DevinWalker @kevinwhoffman @ravinderk 

I've researched on this and found that currently there is no way to add custom post status to Publish meta box. I've found 8 years old [open Trac ticket ](https://core.trac.wordpress.org/ticket/12706) which is still under `Future Release` label.

Also, I have found an alternative solution to implement the custom post status to Publish meta box using inline scripts. Refer: http://jamescollings.co.uk/blog/wordpress-create-custom-post-status/
Using this method will increase page load time of all the post detail page due to the less performant code.

I would like to suggest to proceed with the way @DevinWalker suggested in [comment](https://github.com/WordImpress/Give/issues/2250#issuecomment-370677288) which will be used when required. 

Let me know your thoughts on this.

**Comment by kevinwhoffman** [comment]
I think it is fine if the `publish_closed` status does not appear in the Publish meta box. After all, we do not want users manually changing this status anyways; we only want it changed when a goal is met and set to close. This status doesn't need to be visible to the end user. It just needs to be set in the event that a user wants to exclude forms that are closed from their query.

The suggestion in https://github.com/WordImpress/Give/issues/2250#issuecomment-370677288 does not address the need to query forms by closed status. It only provided the functionality to check if an individual form is closed.

If we want to avoid the post status solution, then the alternative would be post meta or hidden taxonomy, but post status is the simplest query from a MySQL perspective.

**Comment by ravinderk** [comment]
@kevinwhoffman yes `post_status` will be simplest but it will increase complexity at the core.

I think if we will use post_meta logic then it will be clean. Since we are using custom meta table, so performance will not be a big issue. On basis of custom meta, we can show custom post status on form edit screen which will inform admin about form status.

@kevinwhoffman let me know what do you think

**Comment by kevinwhoffman** [comment]
@ravinderk @mehul0810 Let's go with the post meta approach. Seems like the path of least resistance and will get the job done.

I recommend we use `_give_form_status` as the post meta key with a value of `closed` if the form is closed. This will leave flexibility if we have other form statuses in the future.

Updated tasks below:

- [ ] Hook into completed donations to check if a goal is enabled, set to close when completed, and complete. If so, then set `_give_form_status` to `closed`.
- [ ] Write an upgrade routine for 2.1 that loops through all forms and sets the post meta if closed.
- [ ] Add `status` attribute to the `[give_form_grid]` shortcode. By default, the shortcode should display all published forms, but if `[give_form_grid status="open"]` is used, then a meta query should be added to excludes `closed` forms.

**Comment by mathetos** [comment]
Bummer. The custom post_status option sounded pretty great.
