### ISSUE TITLE
Add filter when getting payment amount 

### ISSUE THREAD

**Issue by emgk** [WordImpress/Give#2317]
## Issue Overview
Ref: #2316

## Expected Behavior
FIlter amount when using the get_payment_amount function.

## Current Behavior
There is no filter to filter out the payment amount.

## Todos
- [x] Tests
- [x] Documentation

**Comment by ravinderk** [comment]
@emgk I am reopening this issue because it is related to https://github.com/WordImpress/Give/issues/2360.

Currently, we have to think about introducing new param (`$type`) in donation amount related function

@mehul0810 Please fix following things:
1. Revert `$type` changes in donation fn.
2. Deprecate `give_get_payment_amount`
3. add `Give_Payment` object support to `give_donation_amount` fn
