### ISSUE TITLE
feat(test): improve UI testing

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2350]
## Issue Overview
These two tools look like it makes it a lot easier to build UI tests for Give. This would be complimentary to the unit test suite already in place.

### Repos

https://github.com/segmentio/nightmare
https://github.com/segmentio/daydream

### Information

https://segment.com/blog/ui-testing-with-nightmare/
http://codecept.io/nightmare/

### Questions

1. How is it better than PhantomJS? http://phantomjs.org/
2. How can we have continuous integration?

## Possible Solution

1. Setup consistent and predictable UI testing environment. For instance, using a basic implementation of Underscores or TwentySeventeen.
2. Setup as many form type variations as possible (Set, Multi, Set + Custom, Multi + Custom, etc.)
3. Begin writing basic tests as a proof of concept

**Comment by ravinderk** [comment]
@DevinWalker I researched on this one found that `jest` is a testing framework which we can use which also has `puppeteer` integration.

It is also mentioned on google page:
![image](https://user-images.githubusercontent.com/1784821/43672961-5c1516b0-97d7-11e8-9cf2-b9f905cecc9b.png)

ref:
http://www.npmtrends.com/cypress-vs-jest-util-vs-mocha-vs-nightwatch-vs-webdriverio
https://github.com/smooth-code/jest-puppeteer

**Comment by Sidsector9** [comment]
More reference articles - 

- https://teamgaslight.com/blog/testing-behavior-vs-testing-implementation
- Selenium+Chrome **OR** Puppeteer+Chrome: https://news.ycombinator.com/item?id=16461469
- Drawback of Puppeteer is that it lacks cross-borwser testing - https://github.com/GoogleChrome/puppeteer/issues/1667, whereas Selenium offers testing on a variety of browsers - https://www.seleniumhq.org/about/platforms.jsp

**Comment by Sidsector9** [comment]
- Woocommerce has built their own JS classes for testing and have integrated it with Selenium for E2E testing.
- Automattic's [wp-e2e-tests](https://github.com/Automattic/wp-e2e-tests) uses the TestArmada Suite which provides multiple JS frameworks to integrate with Selenium. Automattic specifically uses Mocha JS.

**Comment by Sidsector9** [comment]
**Call Summary**
---
**Participants**: @ravinderk and @sidsector9
**Topic**: Library to choose for headless browser e2e testing.
**Result**: 
After researching multiple headless browsers, I came across prominent few such as Nightmare which uses Electron Browser, Puppeteer which uses headless Chrome and Selenium which provides cross browser testing, as far as IE v6. At first Selenium looked promising just for it's ability for cross-browser support, but the question that popped was that is cross-browser testing really necessary for Give Core.

As far as front-end testing in Give Core is concerned, we aren't focusing to test the visual presentation, we need to focus on the functionality of the entire plugin. AS long as the page is rendered with correct data and JS works, we don't have to bother about how it is rendered. Because of this reason, we can test it on a single browser.

@ravinderk and I came to the conclusion that it would be better to go with Puppeteer for the following reasons - 
- It is a Google product
- It's popularity has risen rapidly
- Google Chrome is frequently updated 
- Can be used with Travis

**Comment by Sidsector9** [comment]
A test run for logging into wordpress and creating a sample donation form and publishing it - 

https://www.useloom.com/share/2f77a5c2ca784db4b5cc85d08c0e7250

CC: @DevinWalker @ravinderk

**Comment by Sidsector9** [comment]
### Update
I set up travis on my custom repository. I used easyengine to install the LEMP stack:
- Linux (Ubunu/Trusty) 14.04
- NginX
- MySQL
- PHP

One minor issue is that Trusty doesn't come with PHP5.3 but it's available on Precise, but EasyEngine doesn't support Precise. 

For now Continuous Integration works wonderfully, all the necessary dependencies are being installed correctly. I experimented with EasyEngine to achieve automation in a short amount of time so that I can understand Travis better so now only research on moving to Docker is remaining.  Once that is done, we can straight away start writing e2e tests.

C: @ravinderk @DevinWalker
