### ISSUE TITLE
Donor Profile Editor shortcode improvement

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2407]
## Issue Overview

There is the following point where we can improve donor profile editor:
1. Show required field icons for required fields.
2. Show proper error while saving donor fields.
3. Password field is not updating.

Video: http://screencast-o-matic.com/watch/cbXYYw2ZEj

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mehul0810** [comment]
@ravinderk I've noticed that there is an issue in validation with First Name field of `[give_profile_editor] shortcode which is fixed in the created PR.

**Comment by raftaar1191** [comment]
@mehul0810 

Please see this video I am getting an issues http://screencast-o-matic.com/watch/cblf062giu

**Comment by ravinderk** [comment]
@raftaar1191 We can hide billing address field from donation form but they are required if enabled. I think a donor must have a personal address. That why @mehul0810 and I agreed to make `Address` required for donor profile edit form.

@DevinWalker Let us know your view on that.

**Comment by mehul0810** [comment]
@ravinderk @DevinWalker  I think @raftaar1191 is trying to convey that he cannot change the password unless and until the required fields are filled up as the server-side validation occurs based on the sequence of fields from top to bottom. Let me know your thoughts.

**Comment by DevinWalker** [comment]
I understand @mehul0810 and @raftaar1191 - yes that appears to be an issue.

**Comment by mehul0810** [comment]
@DevinWalker I've created a video in which i've showed the issue again and the fix for it which can create another issue and the possible suggestions. Please check the video and let me know your thoughts. Also, let me know, if a quick call is required to discuss further about the issue.

**Video Link:** https://drive.google.com/open?id=11STloZKcNhKHD30h2kd85VOaRpcqU7q1

**Comment by raftaar1191** [comment]
Yes @mehul0810 we can move this to another issue that right, but I think let @ravinderk and @DevinWalker also add there thought on this 


But the address and Password Change are entirely two different section it's should not depend on one another 


Like you can see in the WordPress Admin Section also 
Profile fields and Password Change are coming on the same page but they are not related to one another 
![image](https://user-images.githubusercontent.com/22215595/33649533-415d0438-da84-11e7-8862-0792c86837b6.png)

**Comment by DevinWalker** [comment]
@mehul0810 @raftaar1191 @ravinderk - this issue is getting bumped. I watched Mehul's video and have a few concerns:

1. Why is billing address required? It shouldn't be because many payment gateways don't require it so it shouldn't be within the profile editor.
2. The only required fields should be _first name_ and _email_ 

I'm bumping this as it's not a major concern at the moment but I do want to discuss.
