### ISSUE TITLE
Metabox on Give CPT for layout options

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#245]
End users really need a simple way to customize some of the simple layout options of the single Give Forms. ThemeFoundry's Make theme has a really useful metabox as an example:

![layout-metabox-make](https://cloud.githubusercontent.com/assets/930724/9822007/db9deb7a-5872-11e5-9016-51d4a579dd50.png)

I think we need these basic options:

- [ ] Disable Title
- [ ] Disable Sidebar
- [ ] Disable Featured Image

Here's a couple other options I think would be even more powerful:

- [ ] Sidebar position: left/right
- [ ] Featured image layout: standard/top
- [ ] Choose Page template: A dropdown of the theme's available page templates to use instead of the Give default. The Event's Calendar has this option, but not per event, only globally.

**Comment by DevinWalker** [comment]
Initially I liked this idea but the more I think about it the more I don't like it as much. Why? Because it's adding more clutter to the page and it's only affecting singular view. Give's donations forms are more than that. They can be embedded via a shortcode (most commonly) or used as a widget. A lot of the options you outline will only take place on the singular view which many users don't use. 

Customize the singular view also will become a lot easier with #313

**Comment by mathetos** [comment]
I think I agree particularly when you mention how this primarily affects the single form view.

I think this should be rolled into the "Form Layouts/Skins" Addon idea which isn't fully fleshed out yet. I'll close for now.
