### ISSUE TITLE
Smoothing out email access UX

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2474]
## Issue Overview

A few remaining items I've seen from the merging of https://github.com/WordImpress/Give/pull/2395 related to #2304 and #2023

**UX Improvement:** The donation email screen should send confirmation email and not display any donations. Please watch my video explaining it: https://drive.google.com/open?id=1LvON2JwgN7vQaDGCX7t6_V5U9Z38vCA-

**Additional Question:** How come this code is commented out?  https://github.com/WordImpress/Give/pull/2395/files#diff-55a49c9df604db069c03ecff9b771197R72 `email-login-form.php` L72

## Expected Behavior
- Donor receives email confirmation email after clicking "Verify Email"

## Current Behavior
They are shown the donation history table and have to again click "Confirm Email" before seeing complete history. This is an awkward UX and a potential security issue as you can guess emails and see the most recent donation(s) without actually confirming it.

## Possible Solution
- See video

**Comment by mathetos** [comment]
I just tested this myself. It also needs to be tested with the reCAPTCHA feature enabled, because currently the following happens:

1) After reCAPTCHA is successful, there's a "Verify Email Address" button. That's fine.
2) But when you click on that button, the page refreshes with no success/failure message
3) And no email is sent at all.
