### ISSUE TITLE
fix(admin-setting): check specific `$_POST` variable before save

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2492]
## Issue Overview

I will update description after more research.
For Ref: https://wordpress.org/support/topic/action-failed-please-refresh-the-page-and-retry-3/

**Comment by kevinwhoffman** [comment]
The related issue in the support form determined that Give was calling `die()` under the following conditions:

- `$_POST` is not empty
- Give cannot verify a the `_give-save-settings` nonce

These are overly broad conditions that could be triggered by the existence of any `$_POST` variable and thus cause `die()` to be called as the support forum user described. We can prevent this by being more specific with the conditions which trigger Give to save settings.

## Recommended Solution

Update [this condition](https://github.com/WordImpress/Give/blob/390a4b3bf5c64c5e6274baa7226809796bafa947/includes/admin/class-admin-settings.php#L248) to check for a `$_POST` variable that is specific to Give so that the `save()` method is only called if we are sure Give-related settings are involved.
