### ISSUE TITLE
[Give 2.0] Tooltip on Email settings is confusing

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2652]
## Issue Overview
Examples of confusion:

Offline Donations is disabled. So logically the New Offline Donation email is disabled as well. See here:
![image](https://user-images.githubusercontent.com/930724/34841019-b00c93d2-f6bb-11e7-8bfe-c00113f1bda8.png)

But when you hover over it, the tooltip says:
> This notification is required based on plugin settings
![image](https://user-images.githubusercontent.com/930724/34841053-cbab052e-f6bb-11e7-81bc-968578fc1b4f.png)

The tooltip should instead say:
> This notification is disabled based on plugin settings

Same issue with the Email Access email

## Expected Behavior
The tooltip should be instructive of the actual settings.

## Current Behavior
The current tooltip is confusing when the email is disabled.

**Comment by DevinWalker** [comment]
You bring up a good point @mathetos - if the gateway is disabled, then the email shouldn't even be displayed in the available emails to customize. What do you think @ravinderk ?

**Comment by mathetos** [comment]
@DevinWalker I could go either way. Might be nice to show that the email exists, or just hide it when it's totally forced as unavailable. That would resolve this issue as well for sure.

**Comment by ravinderk** [comment]
@DevinWalker @mathetos I agree that tooltip was confusing that why I updated text. Let me know if you want to update text. This is the general text and you have config param to change it from the email notification.

**We can not remove email from the list because toggle settings like this is confusing to admin.**



<img width="779" alt="screen shot 2018-01-12 at 7 05 54 am" src="https://user-images.githubusercontent.com/1784821/34855703-219133e0-f767-11e7-9d99-c8a04ef94ad4.png">

**Comment by ravinderk** [comment]
@mathetos @DevinWalker Can we close this issue?

**Comment by DevinWalker** [comment]
Yes this was resolved in 2.0 release.
