### ISSUE TITLE
Add pause and restart feature to background update

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2676]
Working branch: https://github.com/WordImpress/Give/tree/feature%2Fupdate-process

**Comment by mathetos** [comment]
I think it's important with this feature that the upgrade routine be smart enough to know where it is in the process of updating when it was paused. Essentially, when paused, and then restarted, it should be able to start up again where it left off, rather than restart from the beginning and potentially over-write new information accidentally.

A couple considerations as well:

1) If the "pause" button is hit and the user leaves the page, there should be a new admin alert that says "You've paused the Give database update process. We highly recommend continuing that process to completion as soon as possible. Click here to continue now."

2) What will the "restart" actually do? Will it check for existing data and skip it if it exists? Or simply migrate all data regardless?

3) Maybe it's most important to detect when the upgrade process gets stuck, and then restart automatically, or provide some sort of error logging for what might potentially have caused the process to get stuck... If it does get stuck, it would be great to give them the option to email us with a quick and easy form with error details.

I'm just thinking of all the way this might fail, and how we can get more actionable information as quickly and easily as possible.

**Comment by raftaar1191** [comment]
@ravinderk 

I guess we should also add this to our error log that the update is completed or not. If not then all the details that are associated with the Updating Process


If stop -> Then Update was stop in between ( .Some Details related to the Update as well )

**Comment by ravinderk** [comment]
@raftaar1191 I added updates log under Tools > Logs > Updates.
Note: it will start working on `2.0` update completed because data is storing into a new table.

**Comment by ravinderk** [comment]
@mathetos I added an update health check on `update restart event`.
It will do following things:
1. Remove update with uncallable function.
2. Add missing update dependency if any.
3. Log update event.

@mathetos Review GitHub branch which I mentioned in issue description.

**Comment by DevinWalker** [comment]
This was closed as the pause / restart feature is now implemented. It's not recommended to actually _use_ at all unless you are _positive_ there's an issue with the update. If there is an issue with the update please implement your backup and contact support@givewp.com
