### ISSUE TITLE
Getting unexpected error message while using tools

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2744]
## Issue Overview

![9qdpb0kswv](https://user-images.githubusercontent.com/1784821/35568414-e5dfbe70-05ee-11e8-8f1d-d4b9f6eaea91.gif)

## Expected Behavior

Either work or show an appropriate error message.

## Current Behavior

Getting error when using any tools.

**Comment by mehul0810** [comment]
@ravinderk @raftaar1191 While performing `Delete Test Payments`, it is working fine and deleted donations and when there is no donation then also it show success message.

While performing `Delete Test Donors and Payments`, it is also working fine. But, when there is no payments, it shows an error message which is not related to it `No data found for export parameters.`

**Comment by raftaar1191** [comment]
@DevinWalker @ravinderk 
I did not fix this comment that is being made by @mehul0810  because we are going to refactor the **Data** & **export** ajax code. This issue is already being created by @ravinderk ( did not find the issues link ).

Will fixed the [comment](https://github.com/WordImpress/Give/issues/2744#issuecomment-361599617) at the time of refactoring the code of **data and export**

**Comment by raftaar1191** [comment]
Fix DB error at the time of deleting the donor after the Give Upgrade is completed 

```
[30-Jan-2018 18:48:47 UTC] WordPress database error Unknown column 'customer_id' in 'where clause' for query DELETE FROM `wpgive_give_donormeta` WHERE `customer_id` = 37 made by do_action('wp_ajax_give_do_ajax_export'), WP_Hook->do_action, WP_Hook->apply_filters, give_do_ajax_export, Give_Tools_Import_Donors->process_step, Give_Tools_Import_Donors->get_data, Give_DB_Donors->delete_by_user_id, Give_DB_Donor_Meta->delete_all_meta
```
