### ISSUE TITLE
doc: define roles of README.md, CONTRIBUTING.md, and Wiki

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#2781]
## Issue Overview

With the addition of webpack to `Give 2.1.0` and the recent addition of the [Git Communication Standards](https://github.com/WordImpress/Give/wiki/Git-Communication-Standards) to the Wiki, we ought to clarify the roles of these documents.

- [README.md](https://github.com/WordImpress/Give/blob/master/README.md)
- [CONTRIBUTING.md](https://github.com/WordImpress/Give/blob/master/CONTRIBUTING.md)
- [Wiki](https://github.com/WordImpress/Give/wiki)

## Nice README Examples

- [Woocommerce](https://github.com/woocommerce/woocommerce/blob/master/README.md) - simple and clean while still getting you where you need to go.
- [yarn](https://github.com/yarnpkg/yarn/blob/master/README.md) - nice breakdown of features at the top followed by sections on Installing, Using, Contributing.

## Related

@DevinWalker began documenting the local development workflow in the `2.1.0` [README.md](https://github.com/WordImpress/Give/blob/release/2.1/README.md), so we should discuss where this content should live.

## Todos
- [ ] Discuss the roles of these documents and opportunities for improvement.

**Comment by DevinWalker** [comment]
1. **README.md** - Used for basic understanding of repo and high level setup instructions. The main purpose is to serve as a general pointer to additional instructions and information within the Wiki. 
2. **CONTRIBUTING.md** - General contribution guidelines for the _public_. This may point to specific wiki sections that are relevant to the audience.
3. **Wiki** - Written mainly for contractors and the development team. The Wiki is intended to help developers understand the project workflow within GitHub + ZenHub.

**Comment by DevinWalker** [comment]
@kevinwhoffman I've added an updated version of my comment above to https://github.com/WordImpress/Give/wiki/Development-Workflow-Overview

We can determine if this is the best place for this information to live. Another discussion point is the role of the add-ons `README.md` files. At this time many just copy over the WP.org readme.txt into markdown format. I think what's best is if we remove the functionality and provide add-on specific setup instructions where applicable. I'm interested to hear thoughts on this. 

For now, I'm going to close this issue out since the bulk of the issue has been taken care of and we can begin iterating on the Wiki.
