### ISSUE TITLE
Design and develop new donation form creation UI

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#281]
The metaboxes are starting to get a bit unwieldy causing users to scroll further and further down the page. I propose customizing the metaboxes on the Give Forms single admin pages with tab functionality like so: 

![give-admin-form-metabox-tabs](https://cloud.githubusercontent.com/assets/1571635/10183587/3346d4b4-66e6-11e5-8d69-6fcc8e4b746a.jpg)

Thoughts?

**Comment by mathetos** [comment]
Here's all my thoughts:

* **PRO** Looks really clean, and I really like less clutter on the page
* **PRO** It feels more designed at the user directly, rather than a bunch of fields on a page
* **CON** Potential for JS conflicts with themes or other plugins that don't play nice
* **QUESTION** Is it so different that users will be confused, or have a negative reaction?
* **QUESTION** Will it be an improvement on form creation? Meaning, I hope users can have a fully-functional basic form with the defaults and just configuring the first tab alone
* **QUESTION** How will it impact future Addons? Hopefully it's still relatively easy to add new fields. And I'm not sure what would happen if there are easy hooks to add new TABS and third-party Addons go crazy with that. (think WooCommerce settings page!)

I'm definitely leaning towards "AWESOME", but I'd like to vet it with a bunch of folks considering how significant of a change it would be. And I -- in NO WAY -- want to make an option to turn it off/on. Either it works for 80% or more of users or we ditch it.

**Comment by DevinWalker** [comment]
Thanks for your responses @mathetos - here's my responses:

1. Agree
2. Agree
3. Yes, possibly - if a theme or plugin adds metaboxes to the single give_forms cpt then they would display below the tabbed metaboxes - I don't suspect JS issues other than metaboxes falling below. Possibly some crazy themes could display them above, but that's already the case then now.
4. Yes, I believe but requires testing
5. Potential for a snafu here... if a user has a bazillion Give Add-ons in the future

**Comment by mathetos** [comment]
We might also need to re-visit the categorization or labelling. Not sure "Terms & Conditions" needs an entire tab dedicated to that.

**Comment by DevinWalker** [comment]
@pryley I would love to hear your thoughts too

**Comment by DevinWalker** [comment]
@mathetos yeah totally... I thought that too. Seems like we can fold that under another tab/metabox

**Comment by kevinwhoffman** [comment]
I'll leave feedback in two scenarios as I think the tabs affect form creation and form editing in different ways.

**Form Creation:** Your existing form creation screen is clear and I don't believe it's too long by default. Scrolling vertically through the fields results in a logical progression that takes you from beginning to end in a way that mimics the front-end user experience, which is a good thing. Adding tabs would break the vertical flow and add a second, horizontal axis to the editing process. It's no longer a single vertical scroll, but a series of scrolling down, then up, then selecting the next tab, etc.

**Form Editing:** However, once you've created a form with donation levels, content,  terms, etc. then the screen can get pretty long and finding a specific field to edit can become cumbersome. Upon returning to the form editor, I can see how the tabs would get me where I want to go quicker than scrolling.

**Conclusion:** Overall I think tabs make new form creation slightly more complex, but reducing the time it takes to edit existing forms makes them a worthwhile addition. I know I always spend more time editing and tweaking existing posts than I do creating new ones, so I support the tabs.

**Comment by pryley** [comment]
I like the concept of tabs, but here are my reservations:

1. Having a tab per meta-box is potentially a bad idea when using smaller screens/devices, and especially if there are not many options in the meta-box.
2. Making a user click a tab to change a setting is an additional step, so from a UX point of view it could be considered counter-intuitive.
3. Non-standard UI

I agree with @mathetos about categorization/labeling and if tabs were implemented I would suggest the following:

1. Even though it seems a bit cluttered, adding a little more css styling can make a big difference.

2. Default to two tabs, one for the primary options, one for the secondary options:

	Primary fields:
	- Donation Type
	- Custom Amount
	- Set Goal
	- Default Gateway
	- Display content

	Secondary Fields:
	- Payment fields
	- Complete Donation Text
	- Disable Guest Donations
	- Register/Login Form
	- Floating Labels
	- Terms and Conditions

3. Make a third tab available for add-on meta-boxes that is only shown if any 3rd-party add-ons exist. Hooks are available for the add-on to add a metabox inside the third tabs. One meta-box per add-on.

**Comment by DevinWalker** [comment]
@kevinwhoffman @pryley you both have given us much food for thought. I'm glad you're in the discussion. We will review each consideration in detail and hopefully come to a logical conclusion together.

**Comment by ibndawood** [comment]
Hey @mathetos and @DevinWalker , thanks for asking !

Only just last week I was thinking about the number of metaboxes that Give form has and I was looking into other popular plugins for ideas. Here is how it looks like in WooCommerce:

![image](https://cloud.githubusercontent.com/assets/179533/10186644/3e45f89c-6770-11e5-9630-3d8559767d75.png)

Here are my thoughts:

* Vertical tabs allow add-ons to be hooked easily and we do not have to worry about tabs coming in second line. However the downside is the real estate available for the tab content. To save real estate we can move the form control description to a tooltip like below example:

![image](https://cloud.githubusercontent.com/assets/179533/10186974/a13a37ae-6772-11e5-8140-4b9ac7139be3.png)

* Horizontal tabs are a pain especially with addons and different languages, the tabs are going to come in second line.

* I believe the editor for form content should be present immediately below the Form title. It is the standard user interface for all post types in WordPress ( In fact when I added a form for the first time I was searching for the editor ). My suggestion would be to remove "Form Content" metabox and let the default editor be present. We can move the **Display Content** option to **Form Display Options* metabox. Like @mathetos suggested, I don't think we need a metabox for "Terms", we can move them to "Display Options" as well.

![image](https://cloud.githubusercontent.com/assets/179533/10186913/402c495c-6772-11e5-801f-6c368dff575f.png)

* I am trying to address @pryley's concerns here. I don't think tabs are non standard UI because WooCommerce users are quite used to the idea of vertical tabs and here is how WooCommerce handles the tabs in smaller screens

![image](https://cloud.githubusercontent.com/assets/179533/10187101/8b880886-6773-11e5-8366-b0b81e398dc4.png)

While I share @kevinwhoffman's thought that the form creation process itself is quite clear and easy and I do not think tabs are 100% necessary at this moment. Looking at the scope of addons and features for future, I think tabs would be a good step for the future. While thinking about tabs, I'd go with vertical instead of horizontal that would address concerns from @pryley and @mathetos.

Let me know your thoughts !

**Comment by pryley** [comment]
Here's an example of what it could look like as a single meta-box with a bit of styling, and using drag-and-drop to rearrange the multi-level donation amounts.

As @ibndawood suggested, you could move each field description to a tooltip. 

You could easily have the layout change on mobile to show the fields full-width with the labels above the fields and the tooltip text showing as a description underneath.

![give-metabox-2](https://cloud.githubusercontent.com/assets/134939/10198530/a8a99d82-67c6-11e5-93cf-87a7ac5c9cbd.png)

As an alternative to tabs, you could use a dropdown to change the metabox content for addons (idea taken from woocommerce)...although, with this kind of layout, having multiple add-on metaboxes might be okay. 

![give-metabox-1](https://cloud.githubusercontent.com/assets/134939/10198523/a4aeca40-67c6-11e5-882c-0ae124f21bd8.png)

Anyhow, just another idea.

**Comment by DevinWalker** [comment]
Wow these are looking really nice. Thanks for taking the time @pryley to comp that up. I like the subtle branding and the cleaner layouts with the descriptions in a tooltip. My only fear is for the Multi-Level Donation options fields that when we release recurring donations it's going to get smooshed real bad with the added fields. The dropdown instead of tabs is compelling also... I fear that some newer users may not have any idea how to switch between but then again WooCommerce handles it this way, correct?

**Comment by mathetos** [comment]
I think we've got TONS of information here now. But not a lot of direction. I think I'll put together an internal document for now and we'll circle back with a new suggestion that takes all these ideas and comments in mind.

Like I mentioned previously, each feature of this new UI should benefit 80% of users or more, or we shouldn't do it. So I think a spreadsheet of features of the UI with Pro's and Con's will help us a ton.

Thanks all for your REALLY informed and REALLY detailed feedback. Seriously amazed how quickly everyone stepped up and helped here. We'll circle back later with a new proposal.

**Comment by DevinWalker** [comment]
@mathetos I'd still like to hear from @pippinsplugins when he has a moment.

**Comment by mathetos** [comment]
@pippinsplugins  I'm circling back on this issue. Would love your perspective on this in general before I jump into putting together a new doc.

**Comment by DevinWalker** [comment]
I'm setting this on the 1.5 milestone. I'd love to declutter the UI as @pryley has demonstrated in his concepts.

**Comment by DevinWalker** [comment]
I hate to bump this, but it's going to have to be in a later milestone as 1.6 is already so full and this requires significant development.

**Comment by DevinWalker** [comment]
"Butterbean" has good example of tabbed metaboxes: http://themehybrid.com/weblog/butterbean-post-meta-framework-beta

**Comment by DevinWalker** [comment]
# Change / Updates Request

The following are the UI changes I'd like to see completed now that we have the Settings API in place and the metabox tabs working nicely. 

## Single Give Forms Metabox Tabs

Here are the wireframes for the changes I would like to see made. I have also attached a PDF for copying a pasting the description text updates. 

### Donation Options
![form tab_ donation options](https://cloud.githubusercontent.com/assets/1571635/18692486/6fd378c4-7f4f-11e6-9a2d-1d7bcaa91d27.png)
 
### Donation Goal
![form tab_ donation goal](https://cloud.githubusercontent.com/assets/1571635/18692489/7a009ebc-7f4f-11e6-9ac3-d347e55e6c5f.png)

### Form Display
![form tab_ form display](https://cloud.githubusercontent.com/assets/1571635/18692497/874c602e-7f4f-11e6-9137-c42e3f4353c2.png)

### Form Content
![form tab_ form content](https://cloud.githubusercontent.com/assets/1571635/18692504/915873a0-7f4f-11e6-8ff9-19cf798dfbea.png)

### Terms and Conditions
![form tab_ terms conditions](https://cloud.githubusercontent.com/assets/1571635/18692507/967a291e-7f4f-11e6-85e7-adf7cb8ee0eb.png)

### Offline Donations
![form tab_ offline donations](https://cloud.githubusercontent.com/assets/1571635/18692515/a4e25300-7f4f-11e6-8252-6f18cdbdcfe3.png)

####Changes

- [ ] Please update strings to match text within wireframes. (I'll do this since I have them not within the wireframes) @devinwalker
- [ ] Update Icons - I'll do this as well. @devinwalker
- [ ] Change “Donation Form Data” metabox title to “Donation Form Options” @ravinderk 
- [ ] Move the “Goal” fields to their own tab called “Donation Goal” underneath “Donation Options” @ravinderk 
- [ ] The “Form Display Options” tab should just be called “Form Display” @ravinderk 
- [ ] “Customize Offline Donations” should be it’s own tab simply called “Offline Donations” and not display if the gateway is not enabled.  @ravinderk 
- [ ] All field descriptions should be italicized @ravinderk 
- [ ] The “Display Style” field is currently incorrectly displayed when the “Set” donation level is selected under the “Donation Options” tab - JS issue - @ravinderk 
- [ ] Update field types to match those in mockup with backwards compatibility  @ravinderk 

Notes:

- For the icons per each metabox tab, is there a way to set that via the API? If not it would be nice to have one with support for font icons, dashicons, etc.   @ravinderk

**Comment by DevinWalker** [comment]
The major bulk of this has been taken care of and I've created a new project to track the remaining issues to optimize and cleanup the new UI/Settings for release 1.8. If interested, you can view that here: https://github.com/WordImpress/Give/issues/1064

Thank for everyone's input and help! 🎉
