### ISSUE TITLE
fix(media-uploads): WP's media uploader is uploading to incorrect directory when Give is active

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2830]
## Issue Overview
Reported on WP.org and I was able to reproduce: https://wordpress.org/support/topic/media-uploading-to-wrong-date/#post-9996779

 It was thought that it was multisite related but I was able to reproduce on a standard install.

**See video:** https://goo.gl/vf2z4E

## Expected Behavior
Standard WP media uploads are unaffected by Give plugin.

## Current Behavior
Uploads are going to an incorrect folder directory.

## Steps to Reproduce (for bugs)
Watch video: https://goo.gl/vf2z4E

**Comment by mehul0810** [comment]
@ravinderk 
After doing research on this issue, I've noticed that code of Give Core is affecting global variable `$GLOBALS['post']` due to which when uploading image manipulates `get_post` fn used in media_handle_upload() when passed with `null` value returns the latest Give Donation Form object - strange behaviour. Still looking what is affecting this to happen.

To check what happens, print `$post` and die() here https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/media.php#L296 and then upload an image and check network tab to see the async-upload response

**Comment by ravinderk** [comment]
@DevinWalker @mathetos This is known bug in WP core. To fix this issue I am using `get_posts` instead of `WP_Query` https://github.com/WordImpress/Give/pull/2831 because `wp_reset_postdata` does not work in admin. 

For Ref: 
https://ryanwelcher.com/2014/11/resetting-post-wordpress-admin/
https://core.trac.wordpress.org/ticket/18408
