### ISSUE TITLE
fix(dashboard-widget): make "this year" display correct count of donations

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#2847]
## Issue Overview
"This Year" is currently showing all donations for all time. It should show just the current calendar year.

## Expected Behavior
It should show just this year, or even better would be to allow the admin to set a fiscal year somewhere in the settings, and just show the fiscal year here.

## Current Behavior
SHows all time donations. 

## Possible Solution
from super user Scott Lewis:

I think the "This year" part of the dashboard widget is just coded wrong. It says:

`give_currency_filter( give_format_amount( give_get_total_earnings(), array( 'sanitize' => false ) ) )`

which looks like total all time earnings to me. If you look at the code for give_get_total_earnings() in `give/includes/payments/functions.php` you will see there is no date bounds in this calculation at all. It is what it says: total earnings but that isn't "last year" which is where it is being used in the dashboard widget.

The other dashboard numbers use:
`give_currency_filter( give_format_amount( $stats->get_earnings( 0, 'last_month' ), array( 'sanitize' => false ) ) )`

where `'last_month'`, `'this_week'` or `'this_month'` are specified.

Changing the widget to use:

`give_currency_filter( give_format_amount( $stats->get_earnings( 0, 'last_year' ), array( 'sanitize' => false ) ) )`

produces the correct total for the past year and is probably what the dashboard widget should be using. 

## Steps to Reproduce (for bugs)
1. In an install with lots of donations spanning multiple years, check the "This year on the dashboard widget
2. It will not correctly display this year.

**Comment by slewisma** [comment]
Slight clarification: for "this year", it should use "this_year" in get_earnings(), not "last_year" as my email to Ben stated. 

The reason for consideration of letting the admin specify their fiscal year is that this_year and last_year refer to calendar years but that may not be what the admin wants to see on the dashboard if they do all their tracking and reporting by fiscal year. Also, this_year should really be labelled "Year to date" if corrected to use this_year since it isn't a whole year unless it is 23:59:59 on 12/31 when the dashboard is viewed.
