### ISSUE TITLE
Adding donation area below the content of every post?

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/Give#286]
Hey

I know that I can add the shortcode to a post and have the donation section show there, but can I add the donation section to the bottom of each post below the content (as if I was adding a shortcode to each post)?

Have a great day!

**Comment by mathetos** [comment]
You can use WordPress' `do_shortcode()` function and add it to your `single.php` template file to add it dynamically to every single page/post. If you want it to ONLY appear on posts you'd have to wrap it in a IF statement like this:

`if ( is_singular('post') ) {
    echo do_shortcode('[give_form id="87"]');
}`

Thanks!

**Comment by DevinWalker** [comment]
Hey @paaljoachim this is up to the theme to do this - you can achieve this multiple ways with Give out of the box - such as with a widget or the shortcode, as you reference. A lot of themes have widgetized footers, so that's one option. Or, you could easily append a shortcode at the bottom of `post.php` or `page.php` in your theme directory. 

I don't think this is the plugins territory though.

**Comment by paaljoachim** [comment]
Thanks guys! 
Btw Add the code to the Give docs so others can also learn how to do this as well.
Thanks again.
