### ISSUE TITLE
fix(donation): detect if amount is already formatted

### ISSUE THREAD

**Issue by emgk** [WordImpress/Give#2874]
## Issue Overview

When formatting amount using `Give.fn.formatCurrency` js fn it returns invalid amount when the passed  amount was already formatted.

![ezgif-3-74f53b1b2b](https://user-images.githubusercontent.com/14994452/37017024-f6cd50e2-2134-11e8-80b3-cad3a31acc05.gif)

## Expected Behavior

- it should returns the same value if the passed amount is already formatted.

## Current Behavior

- Return invalid amount if passed amount which is already formatted.

## Possible Solution

- There should be a function which check if passed amount is formatted or not. 

We have already a `give_maybe_sanitize_amount` fn in PHP code: 
https://github.com/WordImpress/Give/blob/release/2.0.6/includes/formatting.php#L276

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
```
### WordPress Environment ###

Home URL: http://givecurrencyswitcher.com
Site URL: http://givecurrencyswitcher.com
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: givecurrencyswitcher.com
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: ❌ 5.4.45 - We recommend a minimum PHP version of 5.6. See: PHP Requirements in Give
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.5
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: 2.0.2
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: ,
Thousands Separator: .
Success Page: http://givecurrencyswitcher.com/donation-confirmation/
Failure Page: http://givecurrencyswitcher.com/donation-failed/
Donation History Page: http://givecurrencyswitcher.com/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Currency Switcher: ❌ Unlicensed – by WordImpress – 1.0.2
Give - PDF Receipts: ❌ Unlicensed – by WordImpress – 2.2.4

### Other Active Plugins ###


### Inactive Plugins ###

Debug Bar: by wordpressdotorg – 0.9
Debug Bar Post Meta: by whyisjake – 0.5.4
Duplicate Post: by Enrico Battocchi – 3.2.1
Give - Authorize.net Gateway: by WordImpress – 1.3.3
Give - Fee Recovery: by WordImpress – 1.4
Give - Form Field Manager: by WordImpress – 1.2.8
Give - GoCardless Gateway: by WordImpress – 1.1.2
Give - Manual Donations: by WordImpress – 1.3.1
Give - Mollie Gateway: by WordImpress – 1.0.1
Give - PayPal Pro Gateway: by WordImpress – 1.1.4
Give - Razorpay: by WordImpress – 1.1.1
Give - Stripe Gateway: by WordImpress – 1.5.2
Give - Tributes: by WordImpress – 1.4.1
Give - Zapier: by WordImpress – 1.1.2

### Active MU Plugins ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

```
</details>

**Comment by Sidsector9** [comment]
I have questions regarding this issue:

Let's remember the defaults to understand this better.
a ) Currency will exist as an integer OR a floating number, let's call this **Standard Input**
b ) `accounting.js` can accept any of the above two.

## Our configuration

- Currency: `EUR`
- Decimal: `,`
- Thousands: `.` 
- Precision: `0`

## Cases

### Case 1:
Let us use an integer amount of `350400` and `350400.85`

c ) `accounting.js` will accept a Standard Input of amount `350400` and using the above configuration, it will format it to `350.400` Euros
d ) `accounting.js` will accept a Standard Input of amount `350400.85` and using the above configuration, it will format it to `350.401` Euros

_[Note: The outputs are purely floating numbers.]_

**Problem Statement**: `accounting.js` should return the same values if the formatted output from **c)** and **d)** are used as inputs.

Now go back to point **a)**. If we use the outputs from **c)** or **d)** as inputs, it becomes ambiguous for `Give.fn.currencyFormat()` to determine whether the input is Standard Input OR formatted input.

### Case 2:
Precision: `2`

e ) `accounting.js` will accept a Standard Input of amount `350400` and using the above configuration, it will format it to `350.400,00` Euros
f ) `accounting.js` will accept a Standard Input of amount `350400.85` and using the above configuration, it will format it to `350.400,85` Euros

Unlike case 1, here it is at least deterministic that the output is a formatted one and not a Standard one since the decimals occur before the comma.

Even if case 2 is handled, problem with case 1 remains due to ambiguity.

What are your thoughts @emgk @DevinWalker @ravinderk ?

**Comment by emgk** [comment]
This issue was created in order to improve the formatCurrency js fn in Give Core. but as @Sidsector9 mentioned in the comment above, it looks like in `accountants.js` library it hard to check the amount passed to ` formatCurrency` is already formatted or not in various cases.

Since as this is hard to improve formatCurrency fn, we'll need to unformat the amount first then pass into formatCurrency fn that will work and i have implemented this method in Give currency switcher.

**Comment by kevinwhoffman** [comment]
I'm not very familiar with the code base, but rather than trying to interpret the value's characters to know if it's formatted or not, what if we made `amount` an object with the following properties?

- `value` - string - unformatted value
- `formattedValue` - string - formatted value for presentation purposes
- `formatConfig` - object - config used to format the value (currency, decimal, thousands, precision)

In making `amount` an object as described above, we would know the original value, the formatted value, and the config at all times. To detect if the currency was already formatted, we would simply check if the `formattedValue` property was not empty.

**Comment by kevinwhoffman** [comment]
@DevinWalker please weigh in with tasks to resolve this issue so we have clear direction in the next sprint. Thanks.

**Comment by kevinwhoffman** [comment]
Closing after discussion with @DevinWalker. Can reopen later if it becomes a priority.
