### ISSUE TITLE
perf(admin-ajax): research custom ajax handler for speed and reliability

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2929]
## User Story

As a `user`, I want `ajax` to be faster so that `donors` don't have to wait as long to give and I experience fewer issues on slower servers.

## Current Behavior
`admin-ajax` can be slow and we are experiencing nonce issues which I believe is due to caching plugins returning incorrectly cached results. See: https://wordpress.org/support/topic/nonce-error-5/

## Expected Behavior
I expect Give to work at a decent pace on slow $5 servers. Admin-ajax loads a bunch of stuff so it slows down Give in return on my slow server.

## Possible Solution
Create our own AJAX handler with backwards compatibility for add-ons and third-parties.

### Results from Google Searching

1. https://gist.github.com/pixeline/4f234e20f5dc6ca5347f
2. https://gist.github.com/pixeline/4f234e20f5dc6ca5347f
3. https://wordpress.stackexchange.com/questions/213634/how-to-make-custom-ajax-handler
4. https://coderwall.com/p/of7y2q/faster-ajax-for-wordpress
5. https://wp-dreams.com/articles/2014/03/better-ajax-handler-for-wordpress-super-fast-ajax/

## Questions

1. What is Woo/EDD doing about this?
2. Those results above all seem really old, is there a better way to do this that I'm not thinking? For instance, maybe it's better to transition to the WP REST API rather than spend the effort to do this custom handler.
3. What will be the speed difference? Will it be significant?
4. How will support requests be reduced by this? For instance, do caching plugins conflict with admin-ajax? And if so, will they be able to with our custom handler?

**Comment by ravinderk** [comment]
@DevinWalker I found a post about competition between Rest API and admin-ajax.php: https://deliciousbrains.com/comparing-wordpress-rest-api-performance-admin-ajax-php/

**Rest API is slightly faster then admin-ajax.php and this difference becomes when traffic will be high on the server.**

Server caching is one of the reasons for donation form fails to accept the donation. We can overcome server caching issue by:
1. Use REST API calls
2. Contact Support to request a cache exclusion
(Note: cookie and session also sometimes fails due to server caching: https://wpengine.com/support/cookies-and-php-sessions/)

## Questions
**Q: What is Woo/EDD doing about this?**
Ans: We handles donation checkout as EDD does. We can do better by creating REST API routes which also help us to create an APP on top of `Give` code base ( Headless Give 💯 ).
https://woocommerce.github.io/woocommerce-rest-api-docs/

**Q: What will be the speed difference? Will it be significant?**
Ans: Rest API is slightly faster then admin-ajax.php and this difference become when traffic will be high on the server. We can increase it more by loading the only related plugin on API route ( with filter).
https://github.com/dannyvankooten/plugin-endpoints

**Q: How will support requests be reduced by this? For instance, do caching plugins conflict with admin-ajax? And if so, will they be able to with our custom handler?**
Ans: Most of the time donation fails because of server caching and sometimes plugin user is not aware of that and also difficult to modify cache without server support. IF We decide to move to REST API then we will definitely see fewer support tickets.

**Comment by DevinWalker** [comment]
Closing in favor of REST API calls in the future.
