### ISSUE TITLE
feat(admin-donation): resend New Donation email to user-defined list 

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#2949]
## User Story

As a site admin, I want to be able to resend the New Donation email so that those listed as recipients in the email settings will recieve it.

This was a customer request today that would like the ability to resend the new donor emails to outside bookkeepers or other admin.

## Current Behavior
Currently, you can only resend the receipt.

![screen shot 2018-03-23 at 3 23 19 pm](https://user-images.githubusercontent.com/20672471/37849462-36d4ad3a-2eae-11e8-825a-4f9c7ad31563.png)

## Expected Behavior
I expect to be able to do to the donation and resend the email to the current recipients listed in the global or per form email settings.

## Related
https://secure.helpscout.net/conversation/547259548/15894?folderId=1823994

## Tasks
- [ ] Research the feasibility of the issue and document in this issue.

**Comment by slewisma** [comment]
Thanks Sam. To expand on the story, the customer uses Give for donations and WooCommerce for their shop. When a shop order email doesn't deliver or gets deleted by accident, they can open the order and choose to resend the new order notification as an admin action. When a new donation email doesn't deliver or gets deleted by accident, they don't have a similar ability. 

Client's Exchange server was down for 3.5 days due to power failure from heavy snow and high winds. Some notifications never delivered because the retries timed out over that long an outage. Now they don't have an easy way to re-notify the bookkeeper and the person that sends acknowledgements, neither of whom normally login to Wordpress. 

Not an urgent need but seems like an obvious capability that should be there.

**Comment by kevinwhoffman** [comment]
Hey @slewisma thanks for the feature request and extra detail. In your case, with several days worth of donations passing without notifications being sent, I'd suggest exporting the donations from that time period to deliver to the relevant parties. That will probably be more efficient than sending several emails anyways.

You can find the export option I'm referring to under Donations > Tools > Export.

![image](https://user-images.githubusercontent.com/1938671/37850523-d02f0a04-2eb1-11e8-9ea0-f268a5551e19.png)

Just wanted to suggest a quick fix if you need in the meantime. Thanks again.

**Comment by slewisma** [comment]
Thanks Kevin. I already took care of sharing the info. Fortunately there was only 1 donation in that time along with several shop orders. We have some custom form fields (not FFM) that don't export from the exporter (an issue not worth rehashing here --- we'll update the forms to store the meta data the correct 2.0 way as soon as the developer docs / blog are updated to tell us how) so it wouldn't have been the perfect work-around in this case but good suggestion in general.

**Comment by kevinwhoffman** [comment]
I'm going to close this out. Our export tool has improved significantly in the last few releases to the point where you should be able to export almost any field generated by Give core or its add-ons. So if someone needed bookkeeping data for several donations at once, I'd recommend exporting those donations and emailing them as a CSV, rather than resending several individual emails at once.

@slewisma Regarding your request for an updated custom field example, I'm prioritizing that in https://github.com/WordImpress/Give-Snippet-Library/issues/73. Once that snippet is updated, we will carry that over into documentation.
