### ISSUE TITLE
build: resolve issue when running "npm run build"

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2962]
## User Story

As a `developer`, I want to run `npm run build` so that I can `release` the next version knowing it's compiled properly.

## Current Behavior

I current am experiencing an issue with the build process.

## Visuals

![2018-03-27_20-09-52](https://user-images.githubusercontent.com/1571635/38006650-d4705b4e-31fa-11e8-8469-d7870d1822c7.png)

**Comment by Sidsector9** [comment]
@DevinWalker I figured out the issue with the build process, I just need to confirm it from you

**Cause**:
`replace()` is a string function, the reason why the console says `replace()` is not a function is because it is being performed on an object.

Check this line no: [131](https://github.com/WordImpress/Give/blob/release/2.1/includes/admin/class-addon-activation-banner.php#L131) and line [136](https://github.com/WordImpress/Give/blob/release/2.1/includes/admin/class-addon-activation-banner.php#L136)

I don't think we should be translating it using `__()` because it can only accept a string literal and not a variable.

Let me know if I'm correct and I'll fix it asap.
