### ISSUE TITLE
fix(admin-form): max / min  slider appears broken and field title needs updating

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2963]
## User Story

As a `user`, I want the range slider to control the min/max to appear as expected so that I can easily `set the range` of my donation limits.

### Current Visual

The slider appears broken:

![2018-03-27_20-19-25](https://user-images.githubusercontent.com/1571635/38007109-a54e8c12-31fc-11e8-9422-cd550c6c7d9d.png)

## Steps to Resolve Issue

- [x] Resolve issue with appearance of the slider
- [x] Update the field title to be `Max / Min. Amount` since it's not longer just a minimum amount
- [x] Test to ensure the max/min amount range slider works as expected and prevents donations over or under the set range.

**Comment by mehul0810** [comment]
@DevinWalker @ravinderk I think the field title should be `Min/Max. Amount` instead of `Max/Min. Amount` as we will range the amount from minimum to maximum and not vice versa. 
![image](https://user-images.githubusercontent.com/1852711/38788873-199c6ad8-4154-11e8-990f-425c3664805c.png)


I'm re-opening this issue. If the field title is fine for you then close this issue.
