### ISSUE TITLE
Latest update reintroduced a previous bug

### ISSUE THREAD

**Issue by justyn-clark** [WordImpress/Give#300]
I attempted to update to the newest Give version and it broke the WP backend. I attempted to activate the previous version and got the attached error.
 
<img width="1237" alt="screen shot 2015-10-02 at 11 15 33 am" src="https://cloud.githubusercontent.com/assets/11221796/10260853/19bfca6e-6934-11e5-998a-b67842b3c7cb.png">

I was able to temporarily fix the bug by replacing the abstract-shortcode-generator.php with #291 here: https://github.com/WordImpress/Give/blob/ffd9b2c39c8d6976944b84805c431b7a85f12b7f/includes/admin/shortcodes/abstract-shortcode-generator.php

Moving forward I'd like to be able to update without running into errors.

**Comment by DevinWalker** [comment]
We rolled out the fix again in `1.3.0.4` and it'll be in there for good now. Regarding this comment: `Moving forward I'd like to be able to update without running into errors.` - wouldn't we all? Development is complex and there are a lot of moving parts. I hope you can understand we work hard to keep the bugs to a minimum. This issue is due to older versions of PHP we didn't properly account for. We take responsibility for the bug and appreciate our users understanding the importance of first updating on a staging site prior to production.

**Comment by justyn-clark** [comment]
Thanks Devin and I totally appreciate all your hard work. Note taken on staging sites to test updates in the future. 

Great product, as it's been the perfect solution for my client.
