### ISSUE TITLE
feat(admin-tool): add columns for subscription payments number of rene

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#3071]
## User Story

As a `admin`, I want `exports` to have support for my `recurring` information so that I can easily understand `which donations are one time and which are recurring`.

## Acceptance Criteria

- [ ] If _Recurring_ is enabled, additional columns are added to my export 
- [ ] I can view a `Payment Type` that displays several payment types `one time`, `subscription`, `renewal`.
- [ ] I can view a column with the "Subscription Billing Period" (`_give_period`), "Subscription Billing Times" (`_give_times`), and "Subscription Billing Frequency" (`_give_period_interval`).

Notes: Give core should verify Recurring is activated and available.

**Comment by raftaar1191** [comment]
@DevinWalker we should add the code for this in our https://github.com/WordImpress/Give-recurring-Donations/ 

I have developed the code in such a way that it won't be so difficult to do that we just need to add some hook and we are done 


and because of the above this we can then also move the FFM code related to Give Donation Export into it respected add-on 


Let me know you thoughts on this

**Comment by ravinderk** [comment]
Issue moved to [WordImpress/Give-Recurring-Donations #600](https://github.com/WordImpress/Give-Recurring-Donations/issues/600) via [**ZenHub**](https://www.zenhub.com/)
