### ISSUE TITLE
feat(admin): add notice to add-ons warning to always check if Give Core is up-to-date.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#3217]
## User Story

As a `site administrator`, I want `to be aware that Give core needs to be updated before any add-ons` so that `after performing updates all of my add-ons remain active`.

Every major release, the support team gets a handful of tickets from customers panicking because their forms are broken, when in reality it is simply that they updated add-ons before updating core, and the add-ons deactivate themselves.

## Current Behavior
I currently click through and update the plugins, and if I go alphabetically and I am using the Give Authorize.net add-on, it updates before the Give Donation plugin and deactivates itself if it doesn't pass the minimum give version test.

## Expected Behavior

I expect to be warned if a new update to Give core is necessary before updating an add-on.

## Possible Solution

Since the minimum give version check technically happens in the add-on code, this might require issues in each add-on repo, but I was thinking about a way to add aWarning any time Give Core is not on the latest stable version to the top of the plugins page, or to the top of each add-on's listing (search for `give-` in the list?) warning to update core first.

## Steps to Reproduce
1. Downgrade Give to 1.8.x
2. Try to update the recurring add-on to the latest.
3. It'll deactivate.

## Tasks

- [ ] warn user they are about to update when Give is not on the latest version.

**Comment by ravinderk** [comment]
@DevinWalker Here are my suggestion to resolve this issue:

I think we do not need to add code to each addon to show warnings it can be done by core only. To achieve that I need following data:
1. Minimum Give version requirement
2. Tested up to which Give the version

We can insert this information into `readme.txt` file in plugin header with the following tag:
`Give requires at least`
`Give tested up to`

I will prefer to show two notice:
1. It will appear when new `Give` version release. The program will check add-ons `readme.txt` file and warn admin about there addon compatibility with the latest release. 
Exmplate from woocommerce
![wordpress-plugin-update-notice-1920x634](https://user-images.githubusercontent.com/1784821/40422192-280ac2f2-5eac-11e8-84a7-c9d487623d9b.jpeg)

2. It will appear when any addon update release. We will check `readme.txt` file of coming release and show notice if required.
![image](https://user-images.githubusercontent.com/1784821/40422502-314a73f2-5ead-11e8-94b9-0b12594bd24f.png)

**Comment by kevinwhoffman** [comment]
@ravinderk This looks good to me. For the plugin header, let's use the following names to be consistent with the standard plugin file header names:

- `Give Minimum Version` - the minimum version of Give core required to fully activate the add-on.
- `Give Tested Version` - the latest version of Give core the add-on has been tested with.

-----

The add-on notice example shown under Give - Email Reports will be a welcome addition.

But I have some concerns about the Give core notice demonstrated here:

![image](https://user-images.githubusercontent.com/1938671/40440925-6f8879cc-5e8d-11e8-9744-c8659a019616.png)

My understanding is the notice would alert the user to a list of add-ons with `Give Tested Version` in the file header. So let's think about a typical update to Give core...

A Give core update is usually accompanied by a few add-on updates, however the majority of add-ons are not updated alongside every Give core update. I'm concerned that every Give core update will show a long list of add-ons that "have not been tested" with the available core update just because their `Give Tested Version` has not been updated. This could result in concerned users who are wary of core updates or get a bad first impression rather than excitement over a new release.

**Comment by DevinWalker** [comment]
This also doesn't resolve the issue of people updating add-ons remotely and never seeing the notice. @ravinderk let's discuss when you get online. Remember, the major issue here is people updating add-ons that require a higher give version that they are not running and then the add-on deactivating. That's what needs to be resolved.

**Comment by ravinderk** [comment]
@Devinwalker I got you.

I researched on how WordPress updates plugin by ajax.

![image](https://user-images.githubusercontent.com/1784821/40459882-7381b0d6-5f21-11e8-8af8-31286d0ec6ec.png)


We can use `upgrade_pre_install` filter to set custom error message.

![image](https://user-images.githubusercontent.com/1784821/40459867-607f88be-5f21-11e8-8e66-202f3ae35d10.png)

To review how we can remotely update the plugin, I reviewed https://wordpress.org/plugins/shift8-remote-update/  plugin and found that they are following WordPress logic:

![image](https://user-images.githubusercontent.com/1784821/40459924-b515170e-5f21-11e8-8a48-becbbd9f52a3.png)

By using `upgrade_pre_install` filter we can stop plugin update if a custom check fail.
Let me know if you have access to any hosting service where we can test implementation.

**Comment by ravinderk** [comment]
@Devinwalker, @mathetos, @kevinwhoffman I disagree with my first point in https://github.com/WordImpress/Give/issues/3217#issuecomment-391318862 comment because our main concern is addon update

**Comment by raftaar1191** [comment]
@ravinderk 

## Suggestion 
Let create an API in https://givewp.com/ or in Give Core which will contain the Addon as the key and on the other side it will have a `Give Minimum Version` and `PHP minimum version` requirement 

Example: 
{"give-recurring":{"give":"2.1.3","php":"5.3"},"give-stripe":{"give":"2.1.3","php":"5.3"},"give-2checkout":{"give":"2.1.0","php":"5.3"}}

Now before updating the Add-on check for Give minimum version requirement and PHP minimum version requirement if both are update to date update the Add-on or else show an error to admin that you need to update Give Core first

**Comment by ravinderk** [comment]
@rafftar We do not need to create API for that. we have access to readme.txt which we can read.
https://givewp.com/downloads/plugins/give-fee-recovery/readme.txt

**Comment by ravinderk** [comment]
@Devinwalker @mathetos I ran test on infinitewp to check if we will get failed plugin update notice or not and I found that we will get notice for plugin update notice.

Onsite update:
![image](https://user-images.githubusercontent.com/1784821/40481528-541d9176-5f6f-11e8-88fd-424499d9a952.png)

Remote update:
![image](https://user-images.githubusercontent.com/1784821/40481426-1463b024-5f6f-11e8-9fd2-172b9edb227c.png)

Testing site: http://recurring.givewp.com/wp-admin/plugins.php?plugin_status=upgrade

**Comment by raftaar1191** [comment]
@ravinderk 

Can we do the Give Minimum version check before WordPress Enabling Maintenance mode

![image](https://user-images.githubusercontent.com/22215595/40747012-b4691280-6479-11e8-91ab-b53c13905474.png)

**Comment by ravinderk** [comment]
@raftaar1191 We can not do this here because WordPress fire bulk update hook here, in `iframe` even we are updating a single plugin and WordPress enables maintenance mode when we updating the plugin in bulk.

for ref:
https://github.com/WordPress/WordPress/blob/master/wp-admin/update-core.php#L729
https://github.com/WordPress/WordPress/blob/master/wp-admin/update.php#L47
https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-plugin-upgrader.php#L220
