### ISSUE TITLE
fix(form): Be more specific with .notice-dismiss class 

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#3337]
## User Story

As a Give user, I expect that the Give styles will be strong enough to avoid problems like this:

![image](https://user-images.githubusercontent.com/930724/41134297-877fcfcc-6a80-11e8-9e3f-e209890297c0.png)

## Current Behavior
Currently, [this style](https://github.com/WordImpress/Give/blob/a5f8b96eeef37ce20d7efb997f79d37d7708bf29/assets/src/css/frontend/alerts.scss#L8) is very generic, it's just `.notice-dismiss` so it can easily get over-written by other themes or plugins like in the example above.

## Expected Behavior
I expect that Give can avoid this by being more specific in the notices style. 

## Possible Solution
Here's a couple options:

1. img[class*="give"].notice-dismiss {}
2. p.give_notice img.notice-dismiss {}
3. div.give_notices img.notice-dismiss {}

Any of those would help prevent the problem shown above. 

## Related
- HS Ticket: https://secure.helpscout.net/conversation/591988690/19460?folderId=672201

**Comment by kevinwhoffman** [comment]
@Sidsector9 Update [this CSS rule](https://github.com/WordImpress/Give/blob/a5f8b96eeef37ce20d7efb997f79d37d7708bf29/assets/src/css/frontend/alerts.scss#L8-L19) to match the example below. Ideally the class would be prefixed, but we are using it throughout the add-ons so just update the selector and add `!important` like so:

```
.give-notice .notice-dismiss {
    ...
    max-width: 28px !important;
}
```

Please also ensure that the alert in currency switcher has a green bar with green icon. It is currently showing a red border with green icon, which is confusing and looks alarming.

This may require a currency switcher add-on since it is outputting inline styles which are unnecessary since they are already in the front-end stylesheet. If necessary, create an issue for the add-on and address it. Thanks.

## Current

![image](https://user-images.githubusercontent.com/1938671/41136814-fd1808d8-6aa5-11e8-97e7-11805a9ceee1.png)

## Proposed

![image](https://user-images.githubusercontent.com/1938671/41136761-b1cf7820-6aa5-11e8-90ae-538d9e70dc1e.png)

**Comment by raftaar1191** [comment]
## Testing

When testing the Give Core 2.1.5 I find it out that with currency switcher is on we are still getting this issues 

![image](https://user-images.githubusercontent.com/22215595/41519806-e1a4eb76-72e7-11e8-91c4-3ac4961c810f.png)

**Comment by raftaar1191** [comment]
Slack Call Summary

Participants: @Sidsector9 , @raftaar1191
Topic: Regenerate this issues 
Result: Had an call with @Sidsector9 and try to regenerate this issues but not able to regenerate this so closing this issues for now
