### ISSUE TITLE
Update JS with ES6 standard code

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#339]
## Issue Overview

Modernizing our JS is important to ensure we're up to date with current standards and 

### Future Stack

- ES6
- Babel

#### Questions:

- Webpack over gulp?
- jQuery?

**Comment by kevinwhoffman** [comment]
## Phase 1

Phase 1 includes high-level front-end architecture changes. We're setting up the directory structure and pipeline, but we're not worried about refactoring individual assets.

1. Audit existing assets to see if scripts/styles can be broken down better. For example, do all front-end scripts need to be in one file, or can they be broken up?
2. Introduce `webpack.config.js` to replace `gulpfile.js`
3. Split the `assets` directory into `assets/src` and `assets/dist`.
    - `assets/src`
        - `js` - Source JS modules
        - `css` - Sass partials
        - `images` - Source images
        - `fonts` - Fonts
    - `assets/dist`
        - `js` - Compiled/minified/concatenated JS
        - `css` - Preprocessed/minified/concatenated CSS
        - `images` - Minified images
        - `fonts` - Fonts
4. Ignore the `dist` directory which will remove minified assets from version control. Instead build the directory using an npm script.
5. Update the WordPress enqueue calls to use the new directory structure.

## Phase 2

Phase 2 includes refactoring of individual assets to a more modern, class-based architecture made possible by ES6 and webpack. Most of Give's JS assets are currently a collection of expressions that work together without much structure. Furthermore a function in one file cannot be easily used in another file due to every file having its own scope.

If we instead write JS as classes and import them as modules throughout the Give asset pipeline, then we can start to treat our JS as series of interdependent modules rather than a collection of independent files.

## Benefits

- Excluding minified assets from version control will result in a cleaner staging area and commit history. Say goodbye to minified files cluttering the staging area and `Ran Gulp` commits every time you update assets. This new approach will also ensure minified assets are never forgotten since they are generated by a build script prior to release.
- Webpack modules and JS classes mean we can write cleaner and better organized JS where dependencies are handled automatically within the modules themselves. This means we don't have to write complicated globbing patterns like you do with Gulp.
- Webpack is essential for React development, which we will be embracing as Gutenberg nears release. We might as well use it for the rest of Give.
- npm is the standard for node packages, and even the Bower team is recommending transitioning to npm/Yarn. We want to use tech that is maintained and has a long road ahead of it. npm is the present and future as far as I can tell.

## Learning Materials

- [webpack documentation](https://webpack.js.org/concepts/) - good breakdown of key concepts
- [Laracasts webpack course](https://laracasts.com/series/webpack-for-everyone) - good video introduction from the ground up
- [SurviveJS eBook](https://survivejs.com/webpack/foreword/) - a more advanced eBook that assumes integration with React

**Comment by raftaar1191** [comment]
Move https://github.com/WordImpress/Give-Form-Field-Manager/pull/201/files#diff-a0b8932df51abf64f7457c93c4e403f2R3127 `get_parameter ` to Give Core when we reform the Give Core JS


We also have a function related to this type In Give Admin JS
https://github.com/WordImpress/Give/blob/release/2.0/assets/js/admin/admin-scripts.js#L2945 `get_url_params `

**Comment by kevinwhoffman** [comment]
Closing as Phase 1 of the webpack integration is complete in Give core `2.1.0`. Phase 2 (refactoring existing code) can be addressed in smaller targeted issues.
