### ISSUE TITLE
Status change options on the history screen

### ISSUE THREAD

**Issue by rosswintle** [WordImpress/Give#34]
For offline or perhaps failed payments, it would be awesome if the history screen could have a simpler option - such as an AJAX-powered button or link - for marking a donation complete.  I noticed that the "Bulk Actions" menu has options to do this, but it would be great to minimise clicks needed to set donations complete from this screen.

Not critical, but would be a nice enhancement.  It's generally not clear how you would go about setting a pending donation to completed, and takes several clicks once you do know how.

**Comment by DevinWalker** [comment]
After thinking about this more thoroughly I feel this addition would add too much complexity to the UI. WordPress natively doesn't allow the user to publish posts via AJAX in the post listing screen. Why should we provide a similar functionality to the user in a foreign UI? Most users won't expect this or need it and we haven't heard any requests for this feature since so I'm not convinced it's a candidate for inclusion in core.
