### ISSUE TITLE
fix(emails): extend emails functionality to support admin context

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#3516]
## User Story
As a developer, I want to show some email tags for only admin emails so that user can not mistakenly use the admin email tag in the donor emails.

## Current Behavior
I currently cannot set admin context for email tags

## Expected Behavior
I expect to have some kind of functionality with which we can set and display email tags for admin emails only.

## Related
- https://github.com/WordImpress/Give-Stripe/pull/282#issuecomment-407281991

## Tasks
- [ ] Investigate
- [ ] Fix
- [ ] Testing

**Comment by Sidsector9** [comment]
I have fixed this by specifying context for all Email Notifications instead of the default value `all`.

To extend, i.e., add custom contexts such as `admin` through admin in specific Email Notifications, we can use the following code: 

```php
function give_add_admin_context( $config, $obj ) {
	if ( 'new-donation' === $config['id'] || 'email-access' === $config['id'] ) {
		if ( is_array( $config['email_tag_context'] ) ) {
			$config['email_tag_context'][] = 'admin';
		} else {
			$config['email_tag_context'] = array(
				$config['email_tag_context'],
				'admin',
			);
		}
	}

	return $config;
}

add_filter( 'give_email_api_notification_config', 'give_add_admin_context', 10, 2 );
```

This will allow **New Donations** and **Email Access** to have the context of `admin` additionally.

Then the add-on can add an email tag to `admin` context using:

```php
function give_pdf_register_email_tag() {
	give_add_email_tag(
		'stripe_transaction_id',
		__( 'Creates a link to a downloadable PDF receipt', 'give-pdf-receipts' ),
		'give_pdf_email_template_tags',
		'admin'
	);
}

add_action( 'give_add_email_tags', 'give_pdf_register_email_tag' );
```

This way `{stripe_transaction_id}` will only be visible to *New Donations** and **Email Access**

CC: @ravinderk, @mehul0810

**Comment by Sidsector9** [comment]
**Call Summary**
---
**Participants**: @ravinderk and @sidsector9
**Topic**: Alternative way of achieving this
**Result**: Instead of adding a context called `admin`, we can modify the function `give_add_email_tag` to accept an array instead, with a key `is_admin`. The modification of this function should also take care of the backward-compatibility.
