### ISSUE TITLE
fix(gutenberg): error notices shouldn't display on Gutenberg

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#3575]
## User Story

As an `admin` I don't want `Give error notices` displaying on my `Gutenberg editor`.

![2018-08-06_17-07-23](https://user-images.githubusercontent.com/1571635/43746833-726ed3d6-999b-11e8-84a7-e5f77672ecbb.png)

## Current Behavior

Error notices display and are not dismissible. 

## Expected Behavior

Error notices do not appear and disturb my editing.

**Comment by Sidsector9** [comment]
@DevinWalker I'm not able to reproduce this issue, can you have a look at this video - 

https://www.useloom.com/share/c96fbc3fc4324208a466176b92e7723e

**Comment by DevinWalker** [comment]
@Sidsector9 you said you couldn't reproduce it with a video then submitted a PR. This is confusing to me when reviewing. You should delete your comment above with an explanation about how you reproduced it or provide another form of explanation so that it's clear to me.

**Comment by Sidsector9** [comment]
@DevinWalker , even though I'm not able to reproduce the exact issue since the notice is hidden but still rendered, @ravinderk asked to disable all global notices on the Gutenberg editor screen. Hence I submitted the PR.

This is the Slack Chat summary - https://givewp.slack.com/archives/C0FAGC83C/p1533636633000015?thread_ts=1533636447.000184&cid=C0FAGC83C
