### ISSUE TITLE
fix: show donation receipt immediately after donation 

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#3705]
## Current Behavior
Currently, I will see email access form (if enabled) or login form in place of receipt immediately after donation. Few server cached webpage and even do not allow to pass cookies between pages. Give needs cookies information to setup Database session for a donor.

Host on which we detected the issue:
- [x] Pantheon (https://secure.helpscout.net/conversation/666207498/25838/)
- [x] WPEngine ( this host does not allow to set the cookie on cached pages and there are not any workaround like Pantheon except ajax)

## Solution
Few servers allow cookie which has the name with a specific prefix but currently we do not has a filter to edit Give session related cookie. So to solve this issue we have to create new filters which allow the developer to rename session related cookie.

Update
--------
Since WPEngine does not has a workaround to pass cookie between pages, we have to pass the cookie with ajax param (receipt ajax request) and load donor session with that.

Important links:
https://pantheon.io/docs/cookies/

**Comment by ravinderk** [comment]
After `2.2.6` if you want to change session cookie name then you can use `give_session_cookie` filter:
```
add_filter( 'give_session_cookie', '__give_change_session_cookie_name', 10, 2 );
function __give_change_session_cookie_name( $cookie_name,$cookie_type ){
     return "__custom_prefix_{$cookie_name}"; 
}
```

**Comment by mehul0810** [comment]
@ravinderk While working on issue https://github.com/WordImpress/Give/issues/3556 I've noticed that when loggedin with admin and accessing the donation history and then clicking on any of the donation receipt always trigger the latest donation receipt. I doubt that it is fetching the donation receipt from session instead of the actual donation receipt. 

## My findings
Commenting line https://github.com/WordImpress/Give/blob/release/2.3.0/includes/shortcodes.php#L291 solves the problem. But, need to check whether it is impacting any other area or not.

**Comment by ravinderk** [comment]
@mehul0810 This issue has been fixed, testing and close this issue (if fixed)

**Comment by mehul0810** [comment]
Closing this issue as it is working fine as per the commit above by @ravinderk
