### ISSUE TITLE
Add Moroccan currency

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#381]
Request for a new currency

Requested here: https://wordpress.org/support/topic/help-648?replies=1

**Comment by mathetos** [comment]
Moroccan MAD is not supported by PayPal:
https://developer.paypal.com/docs/classic/mass-pay/integration-guide/currency_codes/

This means that regardless of what our reports and the front-end form would say, they would not be accepting payments in MAD, but whatever format their PayPal account defaults to. I don't think we should add any currencies that aren't supported by PayPal out of the box.

**Comment by DevinWalker** [comment]
That's pretty restrictive though. Do all the other currencies we include support PayPal? They could, in theory use Offline Payments (plausible in some countries) or purchase a future gateway that does support that currency (like a lot of the Africa specific ones we have been asked to build).

**Comment by mathetos** [comment]
Yes, I just mean the currencies we support natively in the Core plugin. The Gateway's can add their own currencies that they support beyond what PayPal has. I just think it could make for a very frustrating donor and organization experience to expect a currency then look at your bank statement and see currencies convertion fees or other unexpected activity because it wasn't clear that you were ACTUALLY donating in British Pounds instead of Moroccan MAD.

**Comment by mathetos** [comment]
I dug into this just a little. Looks like our currencies are exactly the supported PayPal currencies in alphabetical order, except for the last four:

![currency-chooser](https://cloud.githubusercontent.com/assets/930724/10976703/158e8a10-83a2-11e5-8a5d-65512842953d.png)

When you set one of those four currencies as your currency in Give (I set it to Indian Rupees), and try to process a payment using PayPal Standard you get this response when submitting the form:

![paypal-wrong-currency](https://cloud.githubusercontent.com/assets/930724/10976732/3e5c4d88-83a2-11e5-965f-a7a2ae1205ad.png)

p.s. That looks like a typo from PayPal -- it should say "This recipient ONLY accepts payments denominated in USD..." Naturally, if PayPal doesn't offer the ability to accept money in Indian Rupees then the recipient can't change that and the donor will continue to get that error message above.

I also just made a donation via PayPal using a U.S. credit card which was converted automatically into CAD (Canadian dollars). That process was seamless and easy. Note that PayPal supports both USD and CAD, this is why they are able to facilitate the currency conversion process and streamline that so well. This would NOT be the case with those 4 additional currencies in the screenshot above.

## Things to consider with currencies

* Perhaps non-standard/supported currencies could still be useful for Offline Donations
* Premium Gateways offer additional currencies, but most likely our Addon for those Gateways should be adding the additional currencies rather than supporting them in the Core plugin.

## Suggestions for how to resolve this

* Remove the currencies from the Core plugin that are not supported by PayPal Standard since using them will cause confusion and render the donation form useless for those users (unless they are ONLY using Offline Donations).
* Use a divider in the Select dropdown to indicate PayPal Standard Supported currencies, and "Other currencies". This type of separator could also be used by Premium Gateway Addons when it is adding additional currencies that the core plugin doesn't support.

![currencies-add-separator](https://cloud.githubusercontent.com/assets/930724/10976924/24c5ec8e-83a3-11e5-9dd0-0a68ad0407ba.jpg)

**Comment by DevinWalker** [comment]
Seeing as we're in a bit of discussion around this ticket I'm going to bump this from 1.3.2 milestone

**Comment by ibndawood** [comment]
@mathetos - This is what I think : 

* We should not list currencies based on support of a payment gateway. 
* The payment gateways should provide that option based on the Give settings (afterall they are Give payment gateways ). So a paypal gateway should check if the existing currency is supported and then make a warning to the user.
* Various gateways support various currencies, so it becomes difficult for us to manage. It is also possible that a user can have one or more gateways enabled.
* I believe we should include as many as currencies as possible and leave the onus to the gateways and the users.
* Here is how WooCommerce does this : https://github.com/woothemes/woocommerce/blob/61e746730fac77ba5ee986d2690ef4dca3f473e1/includes/wc-core-functions.php#L257
* Can also include this function : https://github.com/woothemes/woocommerce/blob/61e746730fac77ba5ee986d2690ef4dca3f473e1/includes/wc-core-functions.php#L320 because more than once I had to add Nigerian Naira to Give.

Those are my $0.2

**Comment by DevinWalker** [comment]
Thanks for your 2 cents @ibndawood - I agree with you on all points.

**Comment by mathetos** [comment]
@ibndawood I like the idea that the gateway should "check if the existing currency is supported and make a warning to the user". That alone would address pretty much all of my concerns. I just want to make sure that the GIve user and the donor have a positive experience with Give, and the screenshots I provided above are not what I'd hope our users to experience.

@DevinWalker Should we change this issue to "Add Alert for currencies currently not supported by installed Gateways"?

**Comment by DevinWalker** [comment]
@mathetos before you do that let me research what it will take to achieve that.

**Comment by ibndawood** [comment]
This is what happened when I activated Paypal with INR.

![image](https://cloud.githubusercontent.com/assets/179533/11084895/b00ff1a0-8866-11e5-821e-63a4761ffd71.png)

**Comment by DevinWalker** [comment]
Interesting... thanks for the screenshot. We'll have to be sure that it's compatible with the future per-form gateway add-on.

**Comment by mathetos** [comment]
I love that. That would help a ton.
