### ISSUE TITLE
Modal window not in mobile viewport

### ISSUE THREAD

**Issue by konus1** [WordImpress/Give#385]
I created a form with the setting that payment fields opens in a modal window.
If I try to use the form on my mobile phone (Android with Chrome Browser), then the modal window is below my current viewport. I have to scroll down to see the window.

The same happens, if  I this as widget into my sidebar (Theme: http://themegrill.com/themes/esteem/)

I am not sure, if this is a bug with my theme only. On my desktop, everything works OK.

**Comment by mathetos** [comment]
Hi Konrad,

Our Github repo is really intended just for development of the plugin, pull-requests, and bugs. Your request is more a support request which we handle at the WordPress Plugin Directory here:

https://wordpress.org/support/plugin/give

Nevertheless, that is by design. Any given Give form might potentially be very LONG specifically on narrow devices, so it's important that the modal be capable of stretching outside the view in order to contain the whole form yet still be scrollable. But if that functionality isn't desired then it might be better to use a link in your sidebar to point your user to the full Give single page instead and use the "Show On Page" display method instead.

**Comment by konus1** [comment]
I am Sorry. My problem was not that the Give form is stretched outside of the view because it is to long. The problem is that the modal window is not visible at all after opening on a mobile device. The user sees the darkend screen only and has no visual hint what he should do. 
Thats why I had the impression that this must be a bug.

**Comment by mathetos** [comment]
I see... do you have a link to the site so I can see the problem live? I have a feeling that's a theme conflict.

**Comment by konus1** [comment]
I created a test site at
http://beta.dd4kids.de/donations/modal-test/
you can also look at it wiht
http://www.responsinator.com/?url=http%3A%2F%2Fbeta.dd4kids.de%2Fdonations%2Fmodal-test%2F


Am 09.11.2015 um 19:27 schrieb Matt Cromwell:
>
> I see... do you have a link to the site so I can see the problem live? 
> I have a feeling that's a theme conflict.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/WordImpress/Give/issues/385#issuecomment-155147429>.
>

-- 
mit freundlichen Grüßen
Konrad Bauckmeier

Steirische Str.55, 01279 Dresden
Tel. 0351/2137976
http://www.dd4kids.de (Tipps für Eltern in Dresden)

**Comment by mathetos** [comment]
OK, I'm pretty sure this is related to the styles your theme has set on lines 427-436:

`
/* Clearing */
.clear:before,
.clear:after,
[class*="content"]:before,
[class*="content"]:after,
[class*="site"]:before,
[class*="site"]:after {
	content: '';
	display: table;
}`

Notice the `class*="content"` rule would be applied to ANY div that has the word "content" in it's class name.

It's hard to test a modal correctly with CSS, but try implementing this:

`
.give-modal .mfp-content:before {
    content: '';
    display: inline-block;
}`

Let me know how that goes.
