### ISSUE TITLE
Add Payment Method Label Settings

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#403]
We get regular requests for customizing the Payment Method labels. Perhaps we should provide Global settings for that. I don't think Per form custom labels is necessary.

**Comment by DevinWalker** [comment]
@mathetos what do you think about this issue now? Do you think the filter snippet we have is sufficient? I don't really want to add options for this since it's a small percentage of users who are requesting them be updated. Most seem happy with "Credit Card", "PayPal", ... and the ones that we choose - if they are not we have the snippets here: https://github.com/WordImpress/Give-Snippet-Library/blob/master/form-customizations/customize-payment-gateway-labels.php

**Comment by mathetos** [comment]
Ya, I think if we have now added filters to all the labels, we're good. I still think a free Addon to customize the labels would be useful. Weekend project ;-)
