### ISSUE TITLE
Thai language doesn't output the Donation Title correctly on the Donation Receipt page

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#421]
See here: 
![thai-language-donation-title-problem](https://cloud.githubusercontent.com/assets/930724/11385156/e5908d4e-92ca-11e5-91f7-8fb7aa236be2.png)

Here's the website: http://buksohn.com/2015/lung/donations/%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%AB%E0%B9%89%E0%B8%AD%E0%B8%87%E0%B8%AA%E0%B8%A1%E0%B8%B8%E0%B8%94/

There do seem to be a few StackExchange tickets related to Thai language and PHP:
* http://stackoverflow.com/questions/12685070/how-to-fix-the-contact-form-encoding-sending-thai-language-using-the-contact-fo
* http://stackoverflow.com/questions/9860869/display-thai-characters-on-page-php-thai-chars-ok-in-db-at-server

Might be a bit difficult to duplicate this issue locally, and potentially it's more a server/hosting configuration issue.

**Comment by DevinWalker** [comment]
I just tried to duplicate this issue locally and am seeing what you're saying with hard to replicate. It's working fine for me:

![2-10-2016 9-31-48 pm](https://cloud.githubusercontent.com/assets/1571635/12970284/75513042-d041-11e5-98d1-682645d409b1.png)

It seems this happens when the DB isn't set to UTF-8

This should solve it but USE WITH CAUTION:

`ALTER DATABASE MyDb CHARACTER SET utf8;`

See: https://codex.wordpress.org/Converting_Database_Character_Sets

Closing this as I don't see much we can do on out end right now to help facilitate this... we should keep an eye out for this issue though.
