### ISSUE TITLE
Improve "Payment Fields" description

### ISSUE THREAD

**Issue by getresults** [WordImpress/Give#48]
End users don't know what a Modal window is.  Let's make this end-user friendly. 

Again - not having seen a form in action yet my first thought is "Upon Click" of what?  What will I need to click on to see the payment fields appear?  Let's improve this description for first time users.

**Comment by DevinWalker** [comment]
I've added "The "Show on Page" option will display the entire form when the page loads. "Reveal Upon Click" places a button below the donation fields and upon clicks slides into view the rest of the fields. "Modal Window Upon Click" is a similar option, rather than sliding into view the fields they will open in a shadow box or "modal" window." to this field's description
