### ISSUE TITLE
Sessions should not be started in WP admin OR switch action to send_headers

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#493]
We are running into conflicts, mainly with the Unyson builder by Themefuse. I can't think of any reason Give sessions should be started in the WP Admin - @mathetos can you? @ibndawood ping!

**Comment by ibndawood** [comment]
@DevinWalker, Do you have any specifics on what type of conflicts ?

**Comment by DevinWalker** [comment]
They're using some strange method to display notices via sessions. They start sessions way later than we do and it causes the admin to 500 error.

**Comment by moldcraft** [comment]
Hello @DevinWalker 

It's not a strange method, it's simple:

1. User press Submit
2. We process the form, add a success message in session and do redirect
3. After page refresh, the message is displayed once and deleted from session

Similar to http://symfony.com/doc/current/book/controller.html#flash-messages

----

We inspected the problem and emailed you the solution. Have you received it? From your side the fix is simple, you just need to init the session a bit later (if needed I can find the email)

**Comment by moldcraft** [comment]
Changing [this line](https://github.com/WordImpress/Give/blob/1.3.5/includes/class-give-session.php#L85) to

```php
add_action( 'send_headers', ... );
```

fixes the problem.

**Comment by DevinWalker** [comment]
Sorry - I shouldn't have called it strange. @moldcraft - any downside that you can think of to switchin the action? I always thought sessions should be started on `init`

**Comment by DevinWalker** [comment]
What I'm afraid is that if we switch the action - it will causes session issues with other plugins like Woo / EDD, etc. - note: I haven't tested this...

**Comment by moldcraft** [comment]
Try `wp_loaded`, it is execute a bit earlier (almost right after `init`, on both front and backend) https://codex.wordpress.org/Plugin_API/Action_Reference

**Comment by andronic90** [comment]
Hello Devin,
I tested this on our theme "the core" and now on page refresh all work fine.
Thanks!
