### ISSUE TITLE
feat(donation): add the ability to embed forms using WP's oEmbed 2.0

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#526]
WordPress 4.4 supports oEmbed for post objects. See how Woo does this in their latest version

https://make.wordpress.org/core/2015/10/28/new-embeds-feature-in-wordpress-4-4/

**Comment by ramiy** [comment]
@DevinWalker,

Those are the old filters - they have been added in 4.4.

In 4.5 core added new theme templates, for easier use:

https://make.wordpress.org/core/2016/03/11/embeds-changes-in-wordpress-4-5/

You should also checkout this ticket:

https://core.trac.wordpress.org/ticket/34278

**Comment by ramiy** [comment]
This issue a mystery. I don't know why donation embeds are not working.

Testing the embed view is simple, just add `/embed/` suffix to any WordPress URL (Post, Pages, CTPs). With donations nothing works. No embed view. Can't figure out why.

**Comment by DevinWalker** [comment]
Do you need me to check this one out @ramiy ?

**Comment by ramiy** [comment]
Yes please.

I know how to setup custom embed views. Done this already in other projects.
But I can't figure out why the embed is not working in the first place.

**Comment by kevinwhoffman** [comment]
@DevinWalker Can you clarify the expected behavior? Is the idea to allow any WordPress site to embed a Give form from another WordPress site by pasting the URL to the form?

**Comment by DevinWalker** [comment]
@kevinwhoffman yes exactly, that's the idea.

**Comment by Sidsector9** [comment]
@ramiy  The `/embed` endpoint does not work as intended since Give loads its own [template](https://github.com/WordImpress/Give/blob/release/2.2/includes/class-give-template-loader.php#L39). A minor change in the code fixes this issue.

@DevinWalker I explored the WooCommerce plugin to see how the embed works. The embed shows a preview with a `Buy Now` button, upon clicking it, it will take the user to the actual website. Do you want Give Embedded Forms to function the same way, or do you want the form to be completely functional in the embed itself?

If we go with the 2nd scenario, then we will need to send the scripts and styles data that are used in the front end.

**Comment by Sidsector9** [comment]
@DevinWalker , how should we proceed with this feature? Are we creating a simple Form embed like WooCommerce?

**Comment by DevinWalker** [comment]
@Sidsector9 I'm going to icebox this one for now.

**Comment by DevinWalker** [comment]
Closing until further requests make this more of a priority.
