### ISSUE TITLE
Remove the fr_FR from the extension

### ISSUE THREAD

**Issue by fxbenard** [WordImpress/Give#618]
Hey,

can you remove the fr_FR files from the plugin languages folder as we hit 100% on translate.wordpress.org and the language pack is now effective.

Thanks to all French polyglots! https://translate.wordpress.org/locale/fr/default/wp-plugins/give
A little message in next changelog will be nice ;)

Thanks

**Comment by mathetos** [comment]
Wow! Thanks so much for all your work @fxbenard and French polyglots! 

Just for clarification, we'll need to remove it from the plugin files as a point release in order for users to update to that release and THEN they will see the full French translation from .org? Is that right?

Also, since I have you here, is there official documentation on contributing to plugin language files through the new translate.wordpress.org Glotpress system? I'd like to help our users understand that better to help encourage more languages. Thanks!

**Comment by fxbenard** [comment]
You're right, just remove the fr_FR files from your languages folder. 
The file is already updated for all French users (in wp_lang/plugins/..) but your file is prioritize. Kind of a opt-out system from translate.wordpress.org.

more infos here: https://make.wordpress.org/meta/handbook/documentation/translations/
