### ISSUE TITLE
No Paypal email throws an Undefined Index warning after successful donation

### ISSUE THREAD

**Issue by bryanmonzon** [WordImpress/Give#63]
Maybe replace with a warning when the form is loaded on to the page and prevent the form from being submitted until the admin has entered their email. 

![image](https://cloud.githubusercontent.com/assets/237399/6747082/274c2bc0-ce91-11e4-9298-26e863512a2a.png)

**Comment by DevinWalker** [comment]
Definitely an issue. Thanks for reporting @bryanmonzon

**Comment by DevinWalker** [comment]
Perhaps the gateway shouldn't even be enabled until the admin enters their email?

**Comment by bryanmonzon** [comment]
It looks like EDD just sends you off to Paypal and let's them warn the user. 

![image](https://cloud.githubusercontent.com/assets/237399/6747207/383cb7ea-ce93-11e4-8184-123abd165c37.png)

**Comment by DevinWalker** [comment]
I guessing the same happens without error reporting set to strict.

**Comment by DevinWalker** [comment]
Perhaps an admin warning is better than frontend warning. I feel most users would know to fill out the appropriate fields prior to going live, but ya never know...

**Comment by bryanmonzon** [comment]
It might not even be a big deal. It's probably enough for now to assume the admin should know to enter their email. It would be nice if there was an admin notice that checked if the Paypal Gateway was checked and if there is an email set, though.

**Comment by DevinWalker** [comment]
Indeed that would be nice.

**Comment by ibndawood** [comment]
:+1: I am one of those users who forgot to put in my paypal email. I tested my behaviour with WooCommerce i.e. I did not enter my paypal email address. It did not throw a PHP error instead after filling the info it redirects to paypal page which is throws an error similar to @bryanmonzon 's comment : https://github.com/WordImpress/Give/issues/63#issuecomment-83940284

This is the offending line: https://github.com/WordImpress/Give/blob/master/includes/gateways/paypal-standard.php#L78 . We can simply add a check for index or a more 'WooCommerce' approach would be to initialize like this: https://github.com/woothemes/woocommerce/blob/3e8ba7d591131f23dc17c09740331308c137797a/includes/gateways/paypal/class-wc-gateway-paypal.php#L49 which inherits this: https://github.com/woothemes/woocommerce/blob/master/includes/abstracts/abstract-wc-settings-api.php#L177 and call

**Comment by DevinWalker** [comment]
Guys, I've tested and I think it's fine that we are sending users to the PayPal error page. It provides a description like: 

`We cannot process this transaction because there is a problem with the PayPal email address supplied by the seller. Please contact the seller to resolve the problem. If this payment is for an eBay listing, you can contact the seller via the "Ask Seller a Question" link on the listing page. When you have the correct email address, payment can be made at www.paypal.com.`

Which is fine to tell the user/admin they need to enter their email.

**Comment by mathetos** [comment]
I'm not convinced. I need to test a bit, but I don't think we should have a negative DONOR experience if the Admin is missing something necessary. If we can have a front-end notice like "The PayPal Gateway is not configured. Donations will not be processed" that that both alerts the Admin and the donor in advance instead of having the donor fill out information that is just going to lead to an error on a different page.

**Comment by DevinWalker** [comment]
We'd have to do this for every gateway then that potentially couldn't be configured properly... which would be cumbersome.
