### ISSUE TITLE
User Role Cleanup

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#662]
Give's custom roles need to be cleaned up and there are some issues with `current_user_can` not working properly. Some of this has already been taken care of in #630 but we should really run an upgrade process to:
1. Remove unnecessary caps such as `give_campaigns` one
2. Remove caps with typos such as `edit_give_formss` 
3. Reset caps with appropriate spelling and only the ones necessary

**Comment by DevinWalker** [comment]
Fixed within PR above

**Comment by DevinWalker** [comment]
I'm noticing more unnecessary / duplicate roles:

![dup-roles](https://cloud.githubusercontent.com/assets/1571635/17492037/fbf74cf8-5d5e-11e6-9d65-280b10ac5ad1.png)

![unnecessary-roles](https://cloud.githubusercontent.com/assets/1571635/17492073/16b01570-5d5f-11e6-9f30-3a6516938bd5.png)

**Comment by DevinWalker** [comment]
https://github.com/WordImpress/Give/blob/master/includes/class-give-roles.php#L150-L152

**Comment by DevinWalker** [comment]
More: 
![screenshot at aug 10 15-37-04](https://cloud.githubusercontent.com/assets/1571635/17573713/0f087746-5f11-11e6-9e36-43eacaa241bf.png)

**Comment by Benunc** [comment]
Considering writing my next Give article on Give User roles. have we gotten things cleaned up here yet, enough to post a how-to on Give user roles?

**Comment by mathetos** [comment]
@DevinWalker and @Benunc Just a point of clarification, the screenshots above are not pointing out Give "ROLES" but capabilities. Just want that to be clear.

**Comment by DevinWalker** [comment]
yeah it's fine to move forward with the article.

**Comment by Benunc** [comment]
OK, I set out to write this article, but I feel like we need to dramatically overhaul especially the lower give roles like "worker" 

Here's my proposal: 

A Give worker never needs to see sensitive data, such as a donor's name, or address, or email. They should be able to see the amount given, the date, and the form, but nothing to reveal who the donor is. This includes on the transactions page, and the individual donation detail page. Here's a snippet of code replacing the function here https://github.com/WordImpress/Give/blob/master/includes/admin/payments/class-payments-table.php#L318

```
public function column_default( $payment, $column_name ) {

		$single_donation_url = esc_url( add_query_arg( 'id', $payment->ID, admin_url( 'edit.php?post_type=give_forms&page=give-payment-history&view=view-order-details' ) ) );
		$row_actions         = $this->get_row_actions( $payment );
		$sensitive_data      = current_user_can('view_give_sensitive_data');

		switch ( $column_name ) {
			case 'donation' :
				ob_start();
				?>
				<a href="<?php echo $single_donation_url; ?>" data-tooltip="<?php esc_html_e( 'View details', 'give' ) ?>">#<?php echo $payment->ID; ?></a>&nbsp;<?php _e( 'by', 'give' ); ?>&nbsp;<?php if ($sensitive_data){ echo $this->get_donor( $payment );} else {echo '(hidden)';}; ?>
				<br>
				<?php if($sensitive_data) { echo $this->get_donor_email( $payment );} else {echo '';} ?>
				<?php echo $this->row_actions( $row_actions ); ?>
				<?php
				$value = ob_get_clean();
				break;

			case 'amount' :
				$amount = ! empty( $payment->total ) ? $payment->total : 0;
				$value  = give_currency_filter( give_format_amount( $amount ), give_get_payment_currency_code( $payment->ID ) );
				break;

			case 'donation_form' :

				$value = '<a href="' . admin_url( 'post.php?post=' . $payment->form_id . '&action=edit' ) . '">' . $payment->form_title . '</a>';
				$level = give_get_payment_form_title( $payment->meta, true );

				if ( ! empty( $level ) ) {
					$value .= $level;
				}

				break;

			case 'date' :
				$date  = strtotime( $payment->date );
				$value = date_i18n( get_option( 'date_format' ), $date );
				break;

			case 'status' :
				$value = $this->get_payment_status( $payment );
				break;

			case 'details' :
				$value = '<div class="give-payment-details-link-wrap"><a href="' . $single_donation_url . '" data-tooltip="' . __( 'View details', 'give' ) . '" class="give-payment-details-link button button-small" title="' . __( 'View Details', 'give' ) . '"><span class="dashicons dashicons-visibility"></span></a></div>';
				break;

			default:
				$value = isset( $payment->$column_name ) ? $payment->$column_name : '';
				break;

		}
```
This gives the give worker the ability to even re-send the donation receipt without ever being exposed to the donor's email. 

Currently, this code restricts Give Accountants from being able to see that data as well. I am not sure why the accountant would not be able to see sensitive data, and propose they be given that capability by default. 

I will submit a PR for this so that you can see what other changes I propose to secure the back end data from unauthorized folks.

**Comment by DevinWalker** [comment]
@Benunc let's review this together. I have some questions about the approach here and what data can or cannot be viewed
