### ISSUE TITLE
User able to donate minimum amount then custom minimum amount with multi level donation form

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#712]
**User case:** If custom amount is set to larger amount then minimum amount in multi donation form.

<img width="733" alt="screen shot 2016-07-12 at 9 45 29 am" src="https://cloud.githubusercontent.com/assets/1784821/16754947/6e2e9de4-4815-11e6-883a-05c1a6c2e4c5.png">
<img width="782" alt="screen shot 2016-07-12 at 9 45 39 am" src="https://cloud.githubusercontent.com/assets/1784821/16754948/6e3d8b1a-4815-11e6-9621-736898614af0.png">

In this case user can donate minimum amount then custom minimum amount ( minimum amount should be present in multi level donation values), for other amount values we will get error.

![multi donation form](https://cloud.githubusercontent.com/assets/1784821/16755023/0547e91a-4816-11e6-84d6-4b4bb3b34436.gif)

**My questions**
1. Is it necessary to give custom minimum amount setting to user?
2. Can we set minimum amount to minimum amount in multi level donation form?

**Comment by mathetos** [comment]
@ravinderk 

I duplicated this issue with multi-level forms with a custom amount and custom minimum. 

I think the intended behavior for the "Custom minimum Amount" field is to enforce that minimum, so that donors cannot give less than that amount at all. 

So to your questions:

1) Yes, because organizations get charged by the payment gateway for every transaction enforcing a minimum helps them reduce their fees. For example, PayPal charges 2.9% plus $0.30 per transaction. If a donor gives $1, the Org gets only $0.67 which means they lose 31% of that donation to fees. But if that same donor gave at least $10 then they only lose 6% per $10 transaction.

Secondly, thieves who steal Credit Card numbers often look for payment forms that they can test credit card numbers on. They'll use a form that allows for $1 donations and make a payment over and over with different numbers to test them. These are essentially "spam donations". Enforcing a minimum helps prevent those from happening.

2) We should be able to, but clearly you've discovered a new bug. Thanks for reporting this!
