### ISSUE TITLE
Include custom form fields values in CSV donor exports?

### ISSUE THREAD

**Issue by daveis** [WordImpress/Give#744]
Could this feature request be considered in a future update? I greatly need the CSV exports to display all of the data I have captured with my form, not just the core customer/transaction details.

**Comment by Asparagirl** [comment]
+1

**Comment by mathetos** [comment]
@daveis Just a heads up that we slated this for version 1.7 which should be released in early November.

**Comment by daveis** [comment]
@mathetos That is fantastic news! Thanks for the heads up and the great work you do

**Comment by daveis** [comment]
@mathetos - looks like this issue got moved into the 1.9 milestone? So does this mean it's more likely to roll out in 2017 now?

**Comment by drzraf** [comment]
a first part in PR #1287

**Comment by drzraf** [comment]
You **can** currently export custom fields:
`give_pre_setup_payment` put your custom forms/POST in a custom object attribute (but *not* userinfo)
Ex:
```php
/*
  In any case we can hook give_setup_payment but, user_info are reset by built-in filter
  Thus ony give_pre_setup_payment is usable to temporarily stores and transmit the data in a custom object attribute
*/
function PA_give_pre_setup_payment( $give_payment, $payment_id) {
  $give_payment->custom_fields  = $give_payment->payment_meta['user_info']['custom_fields'];
}
add_filter('give_pre_setup_payment', 'PA_give_pre_setup_payment', 10, 2);
```

In `give_setup_payment` store this meta inside WordPress (here use `update_user_meta()` to store inside `wp_usermeta` or `Give_Customer::update_meta` to store inside `wp_give_customers`). Personnally, I choosed the former.

```php
function PA_give_setup_payment( $give_payment, $payment_id) {
  if (! isset($give_payment->custom_fields)) return;
  $customer = new Give_Customer( $give_payment->customer_id );
  // $customer->update_meta() stores inside wp_give_customers
  // var_dump($customer->update_meta('give_custom_fields', $give_payment->custom_fields));
  // update_user_meta() stores inside wp_usermeta
  update_user_meta($customer->user_id, 'give_custom_fields', $give_payment->custom_fields);
}
add_filter('give_setup_payment', 'PA_give_setup_payment', 10, 2);
```

With the above meta are attached to the donor rather than the transaction (as it shown in the old tutorial).
Then add these fields to the donor CSV:

```php
function pa_custom_fields_export_custom_data($data) {
  foreach($data as $i => $exported_user) {
    // load the previously stored meta
    $custom_fields = get_user_meta($exported_user['userid'], 'give_custom_fields');
    if (!empty($custom_fields[0])) {
      $data[$i] = array_merge($exported_user, $custom_fields[0]);
    }
  }
  return $data;
}
add_filter( 'give_export_get_data_customers', 'pa_custom_fields_export_custom_data');
```

And reference the columns you add:
```php
function pa_custom_fields_export_cols($cols) {
        return array_merge($cols,
                     ['civilite' => 'Civilité',
                      'naissance' => 'Date de naissance',
                      'telephone' => 'Téléphone']);
}
add_filter( 'give_export_csv_cols_customers', 'pa_custom_fields_export_cols');
```

This is the very same hook I used in the above PR in order to display the custom fields attached to donors: `give_export_csv_cols_customers`

Go to wp-admin/edit.php?post_type=give_forms&page=give-reports&tab=export: export donor: CSV contains custom fields' columns and values.


I hope all of this could be documented (hook and internal code path lack documentation), upstreamed (PR), and overall improved (avoid the workaround like custom object attribute and need for two-setup*-hooks). Moreover, custom fields may look easier by learning/relying upon WP built-in features and/or ACF)


Hope this help

**Comment by daveis** [comment]
@mathetos - I'm guessing this is more likely for the v2.0 milestone now? I still see it listed under 1.9 but the recent roadmap announcement on the blog looks like this would be part of the v2.0 "Payment Meta and Database Improvements"

**Comment by mathetos** [comment]
Hi @daveis the plan is to push to 2.0 because of the big changes to payment meta. But we also want to create a simple utility plugin that will let you do this in the interim. We're looking into that now. I'll update this issue when that is done.

**Comment by mathetos** [comment]
Hi @daveis @drzraf and @Asparagirl

Just an update on this issue. We are working on resolving this via Give Core but have several large improvements we want to address that relate to custom fields before implementing this feature fully.

So in the meantime, we've created a "CSV Toolbox" for Give which should help you export the data you need. You can learn about it and download it for free here:
https://givewp.com/documentation/add-ons/form-field-manager/give-csv-toolbox/

Let us know if you have further questions at all.

**Comment by DevinWalker** [comment]
Closing as this is now included in Give core

**Comment by elrumordelaluz** [comment]
Is it possible that I don't see the extra fields added via `give_fields_donation_form_after_personal_info` in the export tab as columns to add/remove?

**Comment by kjohnson** [comment]
Hey @elrumordelaluz, as this ticket is closed I would suggest that you reach out to the [GiveWP support team](https://givewp.com/contact-us/), as they are better equipped to troubleshoot potential issues.
