### ISSUE TITLE
Use only one text-domain

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#964]
Seems like the plugin has 3 text-domains (give, cmb2, edd). We should unify all the text-domain to use only the "give" text-domain.

We can change them manually but the next time we update the cmb2 library (or any other external library) they will use the original text-domain.

We need a gulp task to do that automatically.

**Comment by ramiy** [comment]
https://www.npmjs.com/package/gulp-checktextdomain

**Comment by DevinWalker** [comment]
I agree, `cmb2` does include a ton of their own translation files though: https://github.com/WordImpress/Give/tree/master/includes/libraries/cmb2/languages

I think we should phase out `cmb2` like I've proposed here #668 - I also only see 4 strings using `edd` so that will be easy. A gulp task couldn't hurt for the future.

**Comment by ramiy** [comment]
If you mentioned it, we should also delete the entire CMB2 languages directory.

**Comment by ramiy** [comment]
Ok, now we can merge. I set the grunt task to "**correct_domain: true**"

**Comment by DevinWalker** [comment]
Thanks!
