### ISSUE TITLE
Create settings update script for settings changes

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#976]
Resolving #962 creating a new issue. All the instances where "check to disable" where used will break with the new radio buttons because they now use "Enable/Disable" and the value is "on" or "no value".

In discussing this with @DevinWalker he recommended that rather than inverse the values for these settings (which would create tons of developer confusion) we should create an update script in version 1.7 to resolve it.

Here are the affected settings which will need updating via the new script:
### Payment Gateways Tab
- "PayPal IPN Verification" 
### Display Options Tab
- "Disable CSS" 
- "Disable Welcome Screen" 
- "Disable Form Single Views" 
- "Disable Form Archives" 
- "Disable Form Excerpts" 
- "Disable Form Featured Image" 
- "Disable Single Form Sidebar" 
### Emails Tab
- "Disable Admin Notifications"
### Advanced Tab
- "Disable the_content filter"

**Comment by DevinWalker** [comment]
Ravinder took care of this for #668 - see: https://github.com/WordImpress/Give/pull/1053/commits/d44feb9c3c7886511a4d481deebc0e2e5bd3dc38

**Comment by DevinWalker** [comment]
Sorry, @ravinderk made it clear to me that you're talking about the Settings screen, not the Single Donation Form creation page. Reopening...

**Comment by ravinderk** [comment]
@DevinWalker Here are testing instruction for core settings with new setting api:

### How to test
To test upgrade setting process we need two sites with give plugin already installed, because settings only update once when switch to `release/1.8` and we need fresh `give_settings` before switch to git brach `release/1.8`

Note: I am assuming we have two sites  `give-1` (main testing site) and `give-2` (take fresh `give_settings` from this site).

#### Steps
1. Switch to git branch other then `release/1.8` which have version `< 1.8`.
    a. if you not already tested settings then update settings as you want.

    b. if you already tested settings once then get fresh `give_settings` option value from `give-2` 
and update `give_settings` directly into `give-1` db.  You can also update settings on `give-2` before migrate as you want to test.

2. After updating setting switch git branch to `release/1.8`  and check settings in new setting api.
3. If you do not find any bug/issues , then goto `step 1`.

**Comment by DevinWalker** [comment]
Tested and it's working nicely.
