### ISSUE TITLE
Automate RTL using gulp

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#995]
Custom `rtl.scss` files where temporary solutions to add RTL support (#736).

**The next step is automation**, Converting LTR to RTL automatically using Gulp tasks.

We should implement [gulp-rtlcss](https://www.npmjs.com/package/gulp-rtlcss) or [gulp-cssjanus](https://www.npmjs.com/package/gulp-cssjanus) to do that.

**Comment by DevinWalker** [comment]
Which do you prefer?

**Comment by ramiy** [comment]
gulp-rtlcss

**Comment by mathetos** [comment]
@ramiy Just ran into an issue here. Currently, if you pull down from Give 1.7 there is no rtl.scss. If you run Gulp it looks for it because it's included in the give-frontend.scss import list.

It's a fringe case, but can we make sure to run gulp-rtlcss BEFORE concatenating so we avoid this in the future?

**Comment by ramiy** [comment]
### Loading

The file `includes/scripts.php` loads the CSS/JS files. We don't load any rtl file directly, we load based on language direction using `is_rtl()`

### Generating

Gulp tasks generate CSS files from SCSS files. It generates only regular LTR files.

Later, we use `give-admin.css` to generate `give-admin-rtl.css` file for the backend and `give.css` + `give-rtl.css` for the frontend.

There is no `rtl.scss` file in 1.7 milestone, and it is not included in the `give-frontend.scss` import list.

**Comment by mathetos** [comment]
I think I must not have had my local install totally synced, because you can see the @import for the rtl.scss file here in the give-frontend.scss file: https://github.com/WordImpress/Give/blob/master/assets/scss/frontend/give-frontend.scss#L23

That's on master, and master already has the rtl.scss file present. But locally, I had that give-frontend.scss file, but didn't have the rtl.scss file present. Most likely when 1.7 is pushed to master there will be no weird problems like this at all.

Re-closing for now unless something else like this comes up again. Thanks!

**Comment by ramiy** [comment]
@mathetos

In **Give 1.6** I created a separate RTL file, it was a temporary solution because it requires **manual updates**.

In **Give 1.7** I created a Gulp task to flip the CSS **automatically**.
